### ISSUE TITLE
Dependency is not available in public repo

### ISSUE THREAD

**Issue by vach** [TakahikoKawasaki/nv-websocket-client#1]
Adding dependency in pom does not load it from public repo.

**Comment by TakahikoKawasaki** [comment]
nv-websocket-client 1.3 is available at the Maven Central Repository.

**nv-websocket-client 1.3**
http://search.maven.org/#artifactdetails|com.neovisionaries|nv-websocket-client|1.3|jar

Could you confirm that there is no error in spelling?

**Comment by vach** [comment]
Yes i guess I had some issue with IDE :) 
thanks
