### ISSUE TITLE
Clear OR Close All Connections

### ISSUE THREAD

**Issue by saeedrooyekhat** [TakahikoKawasaki/nv-websocket-client#101]
when i want create new connection how can close all previous  connections that exist?
Actually i don't want create more than one connection. sometimes i need do reconnet , and in this situation i first set null WebSocket (WebSocket=null) for clearing previous connection and after that create a new connection but previous connection is exist yet still.  

how can manage this state and clear or close all connections?

**Comment by TakahikoKawasaki** [comment]
Setting `null` to `WebSocket`? Like this?

    WebSocket ws = ...;
    ws = null;

Assigning `null` to a variable (`ws` in the example above) does not have any effect. It results in that you just lose a reference to the `WebSocket` object which is pointed to by `ws`.

Call `WebSocket.disconnect()` method to close the connection.
