### ISSUE TITLE
Customizable Thread names

### ISSUE THREAD

**Issue by MinnDevelopment** [TakahikoKawasaki/nv-websocket-client#105]
Currently I don't see a way to modify the name of the `ReadingThread` that is created by a WebSocket. (I could just be blind idk)

For our project it would be fairly helpful to change the thread name and maybe add an identifier to differ multiple socket threads from each other to spot issues in our application flow.
Something like `WebSocketFactory#setReadingThreadName(String)` or something similar to that would be greatly appreciated.

**Comment by TakahikoKawasaki** [comment]
Released nv-websocket-client version 2.0 just now. The following callback methods have been added to `WebSocketListener` interface.

- `onThreadCreated(WebSocket, ThreadType, Thread)`
- `onThreadStarted(WebSocket, ThreadType, Thread)`
- `onThreadStopping(WebSocket, ThreadType, Thread)`

For example, if you want to change the name of the reading thread, implement `onThreadCreated()` method like below.

```java
@Override
public void onThreadCreated(WebSocket ws, ThreadType type, Thread thread)
{
    if (type == ThreadType.READING_THREAD)
    {
        thread.setName("READING_THREAD");
    }
}
```

See "Thread Calbacks" in README.md for details.

**Comment by MinnDevelopment** [comment]
Amazing! Appreciate it.

**Comment by DV8FromTheWorld** [comment]
Really appreciate this change.
