### ISSUE TITLE
Per-message-deflate not decompressing incoming messages

### ISSUE THREAD

**Issue by ondrap** [TakahikoKawasaki/nv-websocket-client#108]
It seems to me that there is some problem with the deflate compression. I have just implemented a server that works correctly with the browsers, but doesn't seem to work with this library. It appears that the messages are correctly sent compressed, however when I receive the compressed messages, it seems to me they are either not decompressed or decompressed wrongly (I receive an `onTextFrame` with garbled data).  
Anyone has an idea what's wrong?

**Comment by TakahikoKawasaki** [comment]
Did you call <code>WebSocket.addExtension()</code> like below before calling <code>WebSocket.connect()</code>?

```java
// Enable "permessage-deflate" extension (RFC 7692).
ws.addExtension(WebSocketExtension.PERMESSAGE_DEFLATE);
```

And, what does <code>WebSocket.getAgreedExtensions()</code> say?

```java
@Override
public void onConnected(WebSocket ws, Map<String, List<String>> headers)
{
    List<WebSocketExtension> extensions = ws.getAgreedExtensions();
}
```

**Comment by ondrap** [comment]
I did. The getAgreedExtensions says:
```
[permessage-deflate]
```
And then I get something like:
```
Got text frame: ��V*ILW�RJL�v�(��V�Q�I,.	).I�-P��+�ɩ���
```
Interestingly enough, when I send data using this connection, it appears that the server actually receives it correctly.

**Comment by TakahikoKawasaki** [comment]
Text frame? Not Text **message**? The payload of a text frame may not be a valid string. What does `onTextMessage()` say (not `onTextFrame()`)?

**Comment by ondrap** [comment]
Oops... you are right, onTextMessage works as expected. I have overlooked these are different methods. Thanks.
