### ISSUE TITLE
Websocket interruption accessing "wss://echo.websocket.org"

### ISSUE THREAD

**Issue by MatthewMah** [TakahikoKawasaki/nv-websocket-client#11]
After opening a websocket to "wss://echo.websocket.org", I encounter the following exception:
`com.neovisionaries.ws.client.WebSocketException: Interruption occurred while a frame was being read from the web socket.`

I can open a websocket to other servers without issue, so I suspect this is something particular to echo.websocket.org.

**Comment by TakahikoKawasaki** [comment]
I'm testing `nv-websocket-client` with `wss://echo.websocket.org`, too. But, I've not experienced such an error so far. Are you still suffering from the problem?

**Comment by MatthewMah** [comment]
No, I am not still encountering this problem. Issue appears to have been on the server side.
