### ISSUE TITLE
How can I send files?

### ISSUE THREAD

**Issue by nikitoSha** [TakahikoKawasaki/nv-websocket-client#110]
Hello.
As I know, WebSocket can get files as Blob Frame.
Can you tell me, how can I send files to server?
If not difficult, please, write example?
Sorry for my Russian English (mistakes).
Thanks!

**Comment by szholdiyarov** [comment]
Hi @nikitoSha ,

you can send any message using sendBinary(byte[] message) method.

**Comment by nikitoSha** [comment]
Hi. Thank you, @szholdiyarov !
