### ISSUE TITLE
NaiveSSLContext not working

### ISSUE THREAD

**Issue by coolarm** [TakahikoKawasaki/nv-websocket-client#116]
I am trying to connect to a WS server on my intranet with a self signed certificate. I have used Voley for HTTPS and TooTallNate WS library for WSS and I have been able to set SSLContext to accept all certificates. I am currently switching to nv-websocket-client but, for the love of god, cant seem to bypass SSL certificate verification. I continue to run into the error message "The certificate of the peer...does not match he expected hostname". Its exactly what is in the doc? is something different in v2.2? Here is the code I am using,

`SSLContext context = NaiveSSLContext.getInstance("TLS");`

            ws = new WebSocketFactory().setSSLContext(context).setConnectionTimeout(5000)
                    .createSocket("wss://192.168.1.164/chat/")
                    .addListener(new WebSocketAdapter() {
                        @Override
                        public void onTextMessage(WebSocket websocket, String message) {
                            // Received a text message.
                           }
                        @Override
                        public void onConnectError(WebSocket websocket, WebSocketException e){
                            mTextView.setText(e.getMessage());
                        }
                    });
                    ws.connectAsynchronously();`

**Comment by TakahikoKawasaki** [comment]
The hostname verification was added in the version 2.1. Because the verification is done manually outside `SSLContext`, even `NaiveSSLContext` cannot bypass the verification. If you really need, it is possible to add an option to disable the hostname verification.

**Comment by coolarm** [comment]
Yes, that will be hugely helpful especially when someone's tinkering on a local intranet with a self signed certificate:). Please let me know how.

**Comment by TakahikoKawasaki** [comment]
@coolarm 

Released version 2.3. `getVerifyHostname()` method and `setVerifyHostname(boolean)` method have been added to `WebSocketFactory` class. Execute `WebSocketFactory.setVerifyHostname(false)` to disable the hostname verification. See `README.md` for details.

I've not tested the new methods, but they should work. If you find any problems, let me know.

**Comment by coolarm** [comment]
Awesome sauce! I will give it a shot in the next few days and you can count on me bugging you if I have questions. Thanks once again.

**Comment by DexterLin007** [comment]
it help me.TS

**Comment by AmengGH** [comment]
issue: The certificate of the peer does not match the expected hostname (xxx.com)

solution:

webSocket = new WebSocketFactory().createSocket(uri, 3000);

  java.lang.reflect.Method setHostnameMethod = ((SSLSocket) webSocket.getSocket()) .getClass().getMethod("setHostname", String.class);
setHostnameMethod.invoke((webSocket.getSocket()),"xxx.com");

webSocket.setFrameQueueSize(5)//设置帧队列最大值为5 FRAME_QUEUE_SIZE
                            .setMissingCloseFrameAllowed(false)//设置不允许服务端关闭连接却未发送关闭帧
                            .addListener(new WsListener())//添加回调监听 wsListener 
                            .connectAsynchronously();//异步
