### ISSUE TITLE
Command Response Mismatch issue

### ISSUE THREAD

**Issue by yogeshmudgal** [TakahikoKawasaki/nv-websocket-client#121]
Hi,
I need to use this library in such a way that on every request I need to create a connection and then close it. So when i send multiple commands to my WebServer simultaneously then What i am getting is that the Commands response mismatch.I have handled this issue with that whenever server sends the payload,it will also send me the command name with the response so that i can distinguish that.
         But the problem i am facing is that if I have requested for 3 commands simultaneously and if the response mismatch happens then I do not get the response for all 3 commands.Only 2 commands response i get. When i check the server logs it shows me that it has sent the data. So somehow the problem is on my end. Even the websocket connect closes only 2 times then. 

Please help

**Comment by TakahikoKawasaki** [comment]
Hmm. It is not a WebSocket issue but a software design issue. Please consult a senior software engineer around you.
