### ISSUE TITLE
Performance issue with large (>8KB) messages

### ISSUE THREAD

**Issue by vishwajeetdusane** [TakahikoKawasaki/nv-websocket-client#124]
Thanks @TakahikoKawasaki for the thin websocket protocol specific library for Java. Very easy to use and customize.

While doing a performance benchmark with other websocket library, i noticed for large payload (>8KB) limits TCP frame size to 8KB. Not able to scale TCP.

**Comment by vishwajeetdusane** [comment]
I think primary issue is write(b), which is highly ineffective, 

` private void writeFramePayload(WebSocketFrame frame, byte[] maskingKey) throws IOException
    {
        for (int i = 0; i < payload.length; ++i)
        {
            // Mask
            int b = (payload[i] ^ maskingKey[i % 4]) & 0xFF;

            // Write
            write(b);
        }
    }`

Instead if we 1st apply mask to all elements and then write bulk payload to outputstream would boost the performance significantly. I will try out prototype and update the results.

**Comment by vishwajeetdusane** [comment]
Found the root cause. 
1. writeFramePayload - inefficiently writes a single byte to FilterOutputStream

2. Event after writing bulk payload - FilterOutputStream writes single byte to OutputStream.
[http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/io/FilterOutputStream.java?av=f#120](url)

After fixing this issues, I observed 2X improvement over SSL (SSL/TLS limits packets containing at most 16 KB). With plain connection, limit would be as per TCP windows scale factor and RTT.

**Comment by webfolderio** [comment]
Hi @vishwajeetdusane Could you please share your workaround solution.

**Comment by vishwajeetdusane** [comment]
Instead of using FileterOutputStream, Use BufferedOutputStream class. If the author allows, i can raise a pull request with the change.

**Comment by nikitoSha** [comment]
I have the same issue. When I send big data, server get's this data partly. So, I was change my server's side: read input data while length(data) > 0 and concatenate string.

**Comment by TakahikoKawasaki** [comment]
I'm sorry for not responding long time. I'm too busy as a co-founder of [Authlete, Inc.](https://www.authlete.com/). As requested, I merged PR #217 and released nv-websocket-client 2.11. I hope the new version can solve the issue.
