### ISSUE TITLE
Error: The status line of the opening handshake response is empty

### ISSUE THREAD

**Issue by shihabmi7** [TakahikoKawasaki/nv-websocket-client#127]
After integrating, this web socket I am facing below error, in android.

` E/WebSocketException: WebSocketException
09-19 11:33:36.962 22764-22799/info.androidhive.firebasenotifications W/System.err: com.neovisionaries.ws.client.WebSocketException: The status line of the opening handshake response is empty.
09-19 11:33:36.962 22764-22799/info.androidhive.firebasenotifications W/System.err:     at com.neovisionaries.ws.client.HandshakeReader.readStatusLine(HandshakeReader.java:99)
09-19 11:33:36.962 22764-22799/info.androidhive.firebasenotifications W/System.err:     at com.neovisionaries.ws.client.HandshakeReader.readHandshake(HandshakeReader.java:48)
09-19 11:33:36.962 22764-22799/info.androidhive.firebasenotifications W/System.err:     at com.neovisionaries.ws.client.WebSocket.readHandshake(WebSocket.java:3244)
09-19 11:33:36.962 22764-22799/info.androidhive.firebasenotifications W/System.err:     at com.neovisionaries.ws.client.WebSocket.shakeHands(WebSocket.java:3123)
09-19 11:33:36.962 22764-22799/info.androidhive.firebasenotifications W/System.err:     at com.neovisionaries.ws.client.WebSocket.connect(WebSocket.java:2155)`

**I am integrating this code like below in android.**

[RideActivity.java.txt](https://github.com/TakahikoKawasaki/nv-websocket-client/files/1313153/RideActivity.java.txt)

**Server side code is like below:**

```
var app = require('express')();
var http = require('http').createServer(app);

var io = require('socket.io')(http);


io.on('connection', function(socket){
console.log('client connected');
	let jsonObject = {
		name: 'shihab',
		age : 28
	};

	io.emit('test-event', jsonObject);
	console.log(jsonObject);
});


http.listen(3000, function(){
	console.log('listenting on port 3000');
});
```

**Comment by TakahikoKawasaki** [comment]
Socket.IO and WebSocket are different protocols. Read the document of Socket.IO carefully. If your server speaks Socket.IO protocol, your client has to use a Socket.IO library to talk to the server.
