### ISSUE TITLE
can`t connect tlsv1.2

### ISSUE THREAD

**Issue by hackerLeiWei** [TakahikoKawasaki/nv-websocket-client#13]
Hi , TakahikoKawasaki . Do you know how to connect tlsv1.2 server on android？I tried to connect SSLv3 and TLSv1 successfully。I have said that since API 9 ,some protocols were supported . Besides that , since API 16 , TLSV1.1 and TLSV1.2 are also supported on android . But I can not do it . I`m looking forward that to you can help me to solve it !
Here is my code:

	public SSLContext getSSLContextOld(String imUrl) throws KeyStoreException,
			NoSuchAlgorithmException, CertificateException, IOException,
			KeyManagementException {
		KeyStore keyStore = KeyStore.getInstance("BKS");
		keyStore.load(getInputStream(imUrl), "000000".toCharArray());
		// TrustManager decides which certificate authorities to use.
		TrustManagerFactory trustManagerFactory = TrustManagerFactory
				.getInstance(TrustManagerFactory.getDefaultAlgorithm());
		trustManagerFactory.init(keyStore);
		// Since API 9,the following protocols have been
		// supported:Default,SSL,SSLv3,TLS,TLSv1
		SSLContext sslContext = SSLContext.getInstance("TLSv1.2");
		Log.e(TAG, "protocol-->" + sslContext.getProtocol());
		sslContext.init(null, trustManagerFactory.getTrustManagers(), null);
		return sslContext;
	}

	public void initWs(String imAddress, String encoderToken)
			throws IOException, WebSocketException, URISyntaxException,
			NoSuchAlgorithmException, KeyStoreException, CertificateException,
			KeyManagementException, UnrecoverableKeyException {
		// "wss://domain:port/im"
		String imUrl = imAddress + "?token=" + encoderToken;
		WebSocketFactory webSocketFactory = new WebSocketFactory();
		SSLContext sslContext = getSSLContextOld(imUrl);
		// webSocketFactory.setSSLContext(sslContext);// method 1
		SSLSocketFactory factory = (SSLSocketFactory) sslContext
				.getSocketFactory();//method 2
		webSocketFactory.setSSLSocketFactory(factory);
		webSocket = webSocketFactory
				.setConnectionTimeout(WEBSOCKET_CONNECT_TIME_OUT)
				.createSocket(imUrl).setPingInterval(PING_PONG_INTERVAL)
				// .setPongInterval(PING_PONG_INTERVAL)
				.addListener(webSocketAdapter);
		webSocket.connect();

	}

**Comment by TakahikoKawasaki** [comment]
Read [this answer](http://stackoverflow.com/a/26586324/1174054) in StackOverflow. Below is an excerpt from the answer.

<hr/>
The Android API docs [correctly state](http://developer.android.com/reference/javax/net/ssl/SSLEngine.html) that TLSv1.2 is only supported for SSLEngine in API Level 20 or later (Lollipop) while SSLSocket supports it since level 16.
<hr/>

Ask your question at [StackOverflow](http://stackoverflow.com/).
