### ISSUE TITLE
Query as to disconnect reason

### ISSUE THREAD

**Issue by MadOne199** [TakahikoKawasaki/nv-websocket-client#135]
Hi
I am a self taught programmer using this websocket, so I am no expert on how this works lol.
My websocket disconnects as shown below.  I believe it is correctly working but don't really understand what is causing it to disconnect.  My first guess would be that the timeout was reached, and I think from my code below that means nothing was received for 5 seconds?
Really I am just hoping to understand what is happening better, and ensure that my settings are correct in the code.
I do not control the server, but expect under normal circumstances to receive multiple responses each second from the server.

Can someone please help explain / confirm or correct my thoughts on why the websocket is closing, and advise if I should change anything such as the TIMEOUT?

Thanks in advance...

My Closing websocket response;

Websocket : Websocket State = CLOSING
Websocket : Websocket State = CLOSED
Websocket : Server Close Frame that the server sent to this client = null
Websocket : Server Close Frame that this client sent to the server = WebSocketFrame(FIN=1,RSV1=0,RSV2=0,RSV3=0,Opcode=CLOSE,Length=42,CloseCode=1002,Reason="No more WebSocket frame from the server.")
Websocket : Closed by Server = false

My code for the websocket;

private static final String SERVER = "wss://Something.com/echo/websocket";
private static final int TIMEOUT = 5000;

	public WebSocket connect() throws IOException, WebSocketException
	{
		return new WebSocketFactory()
				.setConnectionTimeout(TIMEOUT)
				.createSocket(SERVER)
				.setPingInterval(2 * 1000)
				.addListener(new WebSocketAdapter() {

					public void onStateChanged(WebSocket websocket,
							WebSocketState newState) {
						System.out.println("Websocket : Websocket State = " +newState);
					}

					public void onDisconnected(WebSocket websocket,
							WebSocketFrame serverCloseFrame,
							WebSocketFrame clientCloseFrame,
							boolean closedByServer) {

						System.out.println("Websocket : Server Close Frame that the server 
                                                sent to this client = " +serverCloseFrame);
						System.out.println("Websocket : Server Close Frame that this client 
                                                sent to the server = " +clientCloseFrame);
						System.out.println("Websocket : Closed by Server = " 
                                                +closedByServer);
					}

					// A text message arrived from the server.
					public void onTextMessage(WebSocket websocket, String message) {
	
						ReadResponse(message);
					} 
				})
				.addExtension(WebSocketExtension.PERMESSAGE_DEFLATE)
				.connect();
	}

**Comment by nikitoSha** [comment]
I have the same problem and don't understand, what's wrong. My WS-server works on node.js (ws library).

**Comment by MadOne199** [comment]
I increased the timeout to 300000 ie 5 minutes, it seemed to make things a lot better for me.  If trading, I found sites saying a 2 or 3 minute lack of incoming data is in fact quite normal. Info found at histdata.com when downloading a file status report for historic data.  For example
`Gap of 147s found between 20171228234124 and 20171228234358.`

**Comment by RISHABHPATNI1108** [comment]
It is not working by increasing timeout, still same issue.

**Comment by taneryilmaz** [comment]
Hi,

I get the `onDisconnected` notification with the reason: **CloseCode=1002,Reason="No more WebSocket frame from the server**

_Stacktrace:_

`0521-122505.965-W-(WebSocketSession) - Disconnected. websocket=com.neovisionaries.ws.client.WebSocket@7d891dd9, serverCloseFrame=nullclientCloseFrame=WebSocketFrame(FIN=1,RSV1=0,RSV2=0,RSV3=0,Opcode=CLOSE,Length=42,CloseCode=1002,Reason="No more WebSocket frame from the server.")
java.lang.Exception: Stack trace
        at java.lang.Thread.dumpStack(Thread.java:1333)
        at icsii.dsreuters.ws.WebSocketSession.onDisconnected(WebSocketSession.java:245)
        at com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:224)
        at com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3758)
        at com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3724)
        at com.neovisionaries.ws.client.WebSocket.onWritingThreadFinished(WebSocket.java:3713)
        at com.neovisionaries.ws.client.WritingThread.notifyFinished(WritingThread.java:539)
        at com.neovisionaries.ws.client.WritingThread.runMain(WritingThread.java:78)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)`



In my case, I receive the same data from the same source with different WebSocket sessions (on different hosts). But some of them sometimes gives above `onDisconnected` case. 

As seen below, Session 1 does not get any data after 13:25:17 and `onDisconnected` is called after 79 seconds. But Session 2 gets data and has no problem.

**Session 1 (on host 1)**

```
0521-132517.718-I-(WebSocketSession) - WSOCK: {instr='TRY=', ASK=8.3706, BID=8.3665}
0521-132517.748-I-(WebSocketSession) - WSOCK: {instr='XAU=', ASK=1885.88, BID=1885.11}
0521-132636.689-W-(WebSocketSession) - WSOCK: Disconnected. closedByServer=false
0521-132636.690-W-(WebSocketSession) - WSOCK: Disconnected. websocket=com.neovisionaries.ws.client.WebSocket@60137160, serverCloseFrame=nullclientCloseFrame=WebSocketFrame(FIN=1,RSV1=0,RSV2=0,RSV3=0,Opcode=CLOSE,Length=42,CloseCode=1002,Reason="No more WebSocket frame from the server.")
java.lang.Exception: Stack trace
        at java.lang.Thread.dumpStack(Thread.java:1333)
        at icsii.dsreuters.ws.WebSocketSession.onDisconnected(WebSocketSession.java:245)
        at com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:224)
        at com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3758)
        at com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3724)
        at com.neovisionaries.ws.client.WebSocket.onWritingThreadFinished(WebSocket.java:3713)
        at com.neovisionaries.ws.client.WritingThread.notifyFinished(WritingThread.java:539)
        at com.neovisionaries.ws.client.WritingThread.runMain(WritingThread.java:78)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Session 2 (on host 2)**
```
0521-132517.280-I-(WebSocketSession) - WSOCK: {instr='XAU=', ASK=1885.94, BID=1884.93}
0521-132517.640-I-(WebSocketSession) - WSOCK: {instr='XAU=', ASK=1886.06, BID=1885.55}
0521-132517.641-I-(WebSocketSession) - WSOCK: {instr='TRY=', ASK=8.3714, BID=8.3663}
0521-132517.732-I-(WebSocketSession) - WSOCK: {instr='TRY=', ASK=8.3706, BID=8.3665}
0521-132517.760-I-(WebSocketSession) - WSOCK: {instr='XAU=', ASK=1885.88, BID=1885.11}
0521-132518.701-I-(WebSocketSession) - WSOCK: {instr='XAU=', ASK=1886.07, BID=1885.56}
0521-132518.701-I-(WebSocketSession) - WSOCK: {instr='TRY=', ASK=8.3716, BID=8.3661}
0521-132518.810-I-(WebSocketSession) - WSOCK: {instr='XAU=', ASK=1885.9, BID=1884.8}
0521-132518.971-I-(WebSocketSession) - WSOCK: {instr='XAU=', ASK=1885.98, BID=1885.21}
```
