### ISSUE TITLE
TCP_NODELAY 

### ISSUE THREAD

**Issue by ange-black69** [TakahikoKawasaki/nv-websocket-client#141]
Hello,
I don't find how to disable the nagle algorithm in the underlying client socket ?
I've a server that running websocket and have nagle disabled.
My client is using a wrapper of nv-websocket-client (https://github.com/czyzby/gdx-lml/tree/master/websocket), I put a issue there, but the author advice me to post here as the wrapper use nv-websocket-client.

Thank you

**Comment by TakahikoKawasaki** [comment]
I hope the following code works.

```
WebSocket ws = ...;
ws.getSocket().setTcpNoDelay(false);
```

**Comment by ange-black69** [comment]
hello Takahiko thank you for your answer,
Fortunately I found a solution to my problem.
In fact, I deploy my game to browser, so I cross-compile with gwt and the web browser automaticaly handle the websocket as TcpNoDelay so no need to explicity define it !
