### ISSUE TITLE
can not connect to the websocket from Lte

### ISSUE THREAD

**Issue by michael-snow** [TakahikoKawasaki/nv-websocket-client#143]
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/TcpOptimizer: TcpOptimizer-ON
                 onStateChanged 
                 onThreadStarted 
                 onThreadCreated 
D/MainActivity: log: onError: com.neovisionaries.ws.client.WebSocketException: Failed to connect to 'wssddd.ddd.ddd:443': connect timed out

**Comment by TakahikoKawasaki** [comment]
A rude issue which just pasted logs.
