### ISSUE TITLE
No more WebSocket frame from the server.

### ISSUE THREAD

**Issue by nikitoSha** [TakahikoKawasaki/nv-websocket-client#145]
Hi. 
I have a WS-server on Node.js (ws library) and client (your Android library).  Server works, client's connection is OK. Client can send messages and  get answers. Ping interval from client to server for 5 seconds. On  client side I don't see "pong" from server. Because of this I set custom  "PONG"-answer from server. Client getting this, OK. But after some time, client disconnects from server with opcode = 1002! And it's happend always after 20 seconds from connecting to server.

> WebSocketFrame(FIN=1,RSV1=0,RSV2=0,RSV3=0,Opcode=CLOSE,Length=42,CloseCode=1002,Reason="No  more WebSocket frame from the server.")

When I make server side on PHP for sockets, I have no this problem. :(  What's wrong?

**Comment by MadOne199** [comment]
maybe try increasing the timeout, worked for me.  Try a big number like 5 mins = 300000
I had the same message, much better after changing Timeout - not seen it since...
`WebSocketFrame(FIN=1,RSV1=0,RSV2=0,RSV3=0,Opcode=CLOSE,Length=42,CloseCode=1002,Reason="No more WebSocket frame from the server.")`

**Comment by fantasysea** [comment]
> Hi.
> I have a WS-server on Node.js (ws library) and client (your Android library). Server works, client's connection is OK. Client can send messages and get answers. Ping interval from client to server for 5 seconds. On client side I don't see "pong" from server. Because of this I set custom "PONG"-answer from server. Client getting this, OK. But after some time, client disconnects from server with opcode = 1002! And it's happend always after 20 seconds from connecting to server.
> 
> > WebSocketFrame(FIN=1,RSV1=0,RSV2=0,RSV3=0,Opcode=CLOSE,Length=42,CloseCode=1002,Reason="No  more WebSocket frame from the server.")
> 
> When I make server side on PHP for sockets, I have no this problem. :( What's wrong?

my project have the same problem,have you solve it ?
