### ISSUE TITLE
Charset specification feature 

### ISSUE THREAD

**Issue by vivek1794** [TakahikoKawasaki/nv-websocket-client#146]
Hi,

I have a requirement where the text and binary data sent from the server is in ISO-8859-1 encoding. This framework by default encodes and decodes data in UTF-8. Is it possible to provide the option to change the encoding format?

**Comment by TakahikoKawasaki** [comment]
RFC 6455, [5.6. Data Frames](https://tools.ietf.org/html/rfc6455#section-5.6) says as follows.

>_Text_
>
>_The "Payload data" is text data encoded as **UTF-8**.  Note that a particular text frame might include partial UTF-8 sequence; however, the whole message MUST contain valid UTF-8.  Invalid UTF-8 in reassembled messages is handled as described in Section 8.1._

Therefore, using ISO-8859-1 encoding for **text** frames is a violation against the specification. Your server would hang up unless you changed the internal implementation of WebSocket of your server.

Regarding **binary** frames, you can send any data, so encoding won't matter.
