### ISSUE TITLE
Minor enhancement request . It would be great to be able to rename the Ping thread.

### ISSUE THREAD

**Issue by kimtuitoek** [TakahikoKawasaki/nv-websocket-client#148]
Since it is possible to change the default names of the Connect, Reading, Writing and Finish thread, it would be great to be able to rename the Ping thread as well.

**Comment by TakahikoKawasaki** [comment]
Released nv-websocket-client 2.5.

2.5 (2018-06-01)
----------------

- `WebSocket` class
    * Added `getPingSenderName()` method.
    * Added `setPingSenderName(String)` method.
    * Added `getPongSenderName()` method.
    * Added `setPongSenderName(String)` method.

**Comment by kimtuitoek** [comment]
Thanks!
