### ISSUE TITLE
Add Websocket Compression using Permessage-Deflate

### ISSUE THREAD

**Issue by vlasky** [TakahikoKawasaki/nv-websocket-client#15]
Hello,

Thanks for creating nv-websocket-client!

I have used your fantastic library to add SSL support to the [Android-DDP client library by delight-im](https://github.com/delight-im/Android-DDP).

It would be fantastic if you could make nv-websocket-client support websocket compression using permessage deflate.

[Meteor 1.2](http://info.meteor.com/blog/announcing-meteor-1.2) recently introduced support for websocket compression using this method. Having support for this feature would greatly reduce the amount of data transferred over the connection.

Here is the official specification document: [Compression Extensions for WebSocket](https://tools.ietf.org/html/draft-ietf-hybi-permessage-compression-28)

**Comment by TakahikoKawasaki** [comment]
Thank you. I'll read the specification.

**Comment by TakahikoKawasaki** [comment]
Dear @vlasky 

I released version `1.17`. It supports [RFC 7692](http://tools.ietf.org/html/rfc7692) (Compression Extensions for WebSocket) aka _permessage-deflate_.

By default, the permessage-deflate support is not enabled. So it needs to be enabled explicitly by calling `addExtension` method.

```java
// Enable "permessage-deflate" extension.
ws.addExtension(WebSocketExtension.PERMESSAGE_DEFLATE);
```

The feature is new and needs testing. Feedback is welcome.

**Comment by smilecs** [comment]
very nice.......

**Comment by vlasky** [comment]
Thank you for adding that so quickly! Look forward to trying it out.

**Comment by TakahikoKawasaki** [comment]
The task to support permessage-deflate itself was done. Please open a new issue if you find bugs in the implementation.
