### ISSUE TITLE
java.util.concurrent.TimeoutException: com.neovisionaries.ws.client.WebSocket.finalize() timed out after 10 seconds

### ISSUE THREAD

**Issue by hncc** [TakahikoKawasaki/nv-websocket-client#157]
java.util.concurrent.TimeoutException: com.neovisionaries.ws.client.WebSocket.finalize() timed out after 10 seconds

 'com.neovisionaries:nv-websocket-client:2.2'

**Comment by TakahikoKawasaki** [comment]
It looks like a network issue which is often observed. What I can say for your short message is only this.
