### ISSUE TITLE
subscribe on topics

### ISSUE THREAD

**Issue by vitaliy-denys** [TakahikoKawasaki/nv-websocket-client#158]
I cannot subscribe on topics

**Comment by chanwenbi** [comment]
please let me any background

**Comment by chanwenbi** [comment]
@vitaliy-denys please let me know any background for your question.

**Comment by vitaliy-denys** [comment]
@Override
public void afterConnected(
  StompSession session, StompHeaders connectedHeaders) {
    session.subscribe("/topic", this);
}

**Comment by TakahikoKawasaki** [comment]
"subscribe to topics"? I'm afraid you are talking about MQTT. WebSocket and MQTT are different.
