### ISSUE TITLE
check is socket connected

### ISSUE THREAD

**Issue by GirishBhutiya** [TakahikoKawasaki/nv-websocket-client#160]
Is there a way to check is socket is connected or not?

Thanks

**Comment by TakahikoKawasaki** [comment]
Maybe, WebSocket.getSocket().isConnected() will work.

**Comment by GirishBhutiya** [comment]
ok Thanks :) :)

**Comment by GirishBhutiya** [comment]
IS there a way to check message is send to server or not?
