### ISSUE TITLE
can't connect

### ISSUE THREAD

**Issue by YanXiaosa5** [TakahikoKawasaki/nv-websocket-client#164]
question:
"The status code of the opening handshake response is not '101 Switching Protocols'. The status line is: HTTP/1.1 302 "   I don't konw the reason ,please help me ,thank you

**Comment by TakahikoKawasaki** [comment]
A WebSocket client expects that the HTTP status code of the response from a WebSocket server is 101, but your WebSocket server returned 302.

In general, when a web browser receives 302, the web browser goes to the location which is written in the `Location` header in the response from the web server.

The WebSocket URL your WebSocket client application accessed returned 302. It means that the WebSocket URL urged your WebSocket client application to access another different URL. Check the value of the `Location` header included in the response from the WebSocket server.

In any case, I'm sorry nv-websocket-client does not support redirection (302).

**Comment by TakahikoKawasaki** [comment]
Sorry, no plan to support redirection.
