### ISSUE TITLE
Android 8.0 when app to background it not work

### ISSUE THREAD

**Issue by liupengandroid** [TakahikoKawasaki/nv-websocket-client#168]
Android 8.0 when app to background it not work, but onDisconnected method not onDisconnected
this is log :W/libEGL: EGLNativeWindowType 0x7e2515b010 disconnect failed

**Comment by RealMoMo** [comment]
Android O add Background Execution Limits : Background Service Limitations & BroadcastLimitations

**Comment by RealMoMo** [comment]
Android O add Background Execution Limits : Background Service Limitations & BroadcastLimitations

**Comment by TakahikoKawasaki** [comment]
Hmm. I don't understand what you want to mean.
