### ISSUE TITLE
Add method to clear out all listeners

### ISSUE THREAD

**Issue by FranciscoE-Reuters** [TakahikoKawasaki/nv-websocket-client#17]
It is only possible to add listeners into the socket, but not remove them. This may cause some problems with lifecycle-bound interactions, i.e. Android activities and fragments. Listeners need to be closed/cleaned at some point that's not internally or on a disconnection.

Please provide a manual clearAllListeners() method to do so.

**Comment by TakahikoKawasaki** [comment]
Thank you for your request. I added `removeListener(WebSocketListener)` method and `clearListeners()` method to `WebSocket` class, and released a new version `1.13`.

**Comment by FranciscoE-Reuters** [comment]
I'm not going to lie, I'm impressed.

Thank you.
