### ISSUE TITLE
Unable to receive Base64 data of incoming messages.

### ISSUE THREAD

**Issue by anhtuantt** [TakahikoKawasaki/nv-websocket-client#176]
Hello eveyrone,
Thank you for the great library, I'm using the library to work with Bibox websocket (crypto currency exchange). Websocket server performs a BASE64 encoding of compressed data, Client decodes BASE64 before decompression. Unfortunately, the client is unable to receive any incoming messages. I was trying to use three method onTextMessage(WebSocket ws, String message) , onTextMessage(WebSocket websocket, byte[] data),onBinaryMessage. None of them worked.

Please give me an advice.
Regards,
Tuan Nguyen.

**Comment by TakahikoKawasaki** [comment]
It would be worth trying other WebSocket client library to investigate which is wrong, the server's implementation or nv-websocket-client's implementation.

**Comment by anhtuantt** [comment]
Yes, let me try and let you know soon.

**Comment by anhtuantt** [comment]
I found the problem. Bibox websocket need a double quote for json format. Thank you for your answer.
