### ISSUE TITLE
Use CopyOnWriteArrayList for Listeners

### ISSUE THREAD

**Issue by eku** [TakahikoKawasaki/nv-websocket-client#18]
The class ```ListenerManager``` should use ```CopyOnWriteArrayList``` instead of ```ArrayList``` to remove the need for locking the list while informing the listeners. Better performance.

**Comment by TakahikoKawasaki** [comment]
Thank you. I didn't know the class.

The version `1.14` contains performance tuning on `ListenerManager` and now the list is not locked while callback methods are called.

**Comment by TakahikoKawasaki** [comment]
The current implementation avoids the old heavy lock by using another different way. Thank you anyway.
