### ISSUE TITLE
Broken compatibility in 2.9 version

### ISSUE THREAD

**Issue by alex-sti** [TakahikoKawasaki/nv-websocket-client#186]
In pre 2.9 versions it was possible to get internal socket object right after socket creation via factory, like in code below:
```
webSocket = new WebSocketFactory().createSocket(url, timeout);
webSocket.getSocket().setReuseAddress(true);
webSocket.getSocket().setTcpNoDelay(true);
```
In 2.9 `getSocket` method returns null, so code above will fail with NPE.

Tested on several android phones and releases, same result

**Comment by TakahikoKawasaki** [comment]
@alex-sti Thank you for your report. The author of the [pull request](https://github.com/TakahikoKawasaki/nv-websocket-client/pull/183) merged into version 2.9 warned me that the pull request contained a change that breaks backward compatibility. The change is what you pointed out exactly. When merging the pull request, I couldn't estimate how the change would affect existing codes. At the same time, the pull request included a new method, `getConnectedSocket()`. It may be able to solve the problem you are facing now.

In normal cases, I don't accept pull requests that break backward compatibility. However, the pull request in question could solve a more important issue for which I would never be able to spare enough time to solve. I'm not sure but the author (@lgrahl) of the pull request may be able to advise you.

**Comment by alex-sti** [comment]
@TakahikoKawasaki Thank you for fast response, tried your suggestion and it helps.   
I assume it would nice to make some tips in readme about that

**Comment by lgrahl** [comment]
@TakahikoKawasaki basically said it all. Using `getConnectedSocket()` hopefully resolves your issue. :slightly_smiling_face: Alternatively, you might be able to provide a `SocketFactory` and set those properties on creation which is probably even cleaner.

**Comment by TakahikoKawasaki** [comment]
I updated README, CHANGES, and JavaDoc of WebSocket.java to mention the backward-compatibility-breaking change introduced by version 2.9.
