### ISSUE TITLE
Fixed NPE if no websocket extensions in server response

### ISSUE THREAD

**Issue by zemlyankin** [TakahikoKawasaki/nv-websocket-client#19]
NPE occurs if no SEC-WEBSOCKET-EXTENSIONS header in server response.
See patch below. I have no permission to create a pull request.

```
diff --git a/src/main/java/com/neovisionaries/ws/client/WebSocket.java b/src/main/java/com/neovisionaries/ws/client/WebSocket.java
index 5d6d485..3b295ac 100644
--- a/src/main/java/com/neovisionaries/ws/client/WebSocket.java
+++ b/src/main/java/com/neovisionaries/ws/client/WebSocket.java
@@ -3220,6 +3220,11 @@ public class WebSocket
      */
     private PerMessageCompressionExtension findAgreedPerMessageCompressionExtension()
     {
+        if (mAgreedExtensions == null)
+        {
+            return null;
+        }
+
         for (WebSocketExtension extension : mAgreedExtensions)
         {
             if (extension instanceof PerMessageCompressionExtension)
```

**Comment by TakahikoKawasaki** [comment]
Thank you for your finding the bug.

BTW, is the settings of nv-websocket-client repository wrong? What is preventing you from creating a pull request? Is it just a policy of the organization you belong to?

**Comment by TakahikoKawasaki** [comment]
Anyway, I applied your patch. Thank you!

**Comment by zemlyankin** [comment]
Hi Takahiko,

When I pushed branch with the fix, I saw the following:

```
$ git push github extensions-npe 
Username for 'https://github.com': zemlyankin
Password for 'https://zemlyankin@github.com': 
remote: Permission to TakahikoKawasaki/nv-websocket-client.git denied to zemlyankin.
fatal: unable to access 'https://github.com/TakahikoKawasaki/nv-websocket-client.git/': The requested URL returned error: 403
```

I'm not familiar with github policies so I'm probably doing something wrong.

**Comment by TakahikoKawasaki** [comment]
Oh (^_^;  You tried to change my repository directly.

First, you need to **fork** `TakahikoKawasaki/nv-websocket-client` to `zemlyankin/nv-websocket-client`. You can find **Fork** button at the top-right corner of GitHub page.

Then, clone the forked `zemlyankin/nv-websocket-client` onto your local machine, create a **branch**, modify source files on the branch, and finally create a pull request.

The above is the normal pull request flow.

**Comment by zemlyankin** [comment]
Thank you! Now it's completely clear.
