### ISSUE TITLE
onDisconnect/onError not called on Android emulators

### ISSUE THREAD

**Issue by ABoschman** [TakahikoKawasaki/nv-websocket-client#20]
I tested out this websocket on Android emulators, but found that the sockets were not getting closed when I turned off the wifi.

What I expected to happen was to instantly get one or more onError calls followed by a onDisconnect call, the moment I shut off the wifi. That is what happens on my physical device (Android 5.0 AKA API 21).

What actually happened was nothing. Nothing happened on further outgoing frames either, it was as if the server simply stopped responding.

I tested this out on [Genymotion(v2.6.0)](https://www.genymotion.com/) emulators running Android API versions 19, 21, 22 and 23, respectively. This is the code I used to open the websocket:
```java
    final WebSocket webSocket = webSocketFactory.createSocket("wss://example.com/websocket");
    webSocket.addListener(new MyWebSocketAdapter());
    webSocket.setPongInterval(45000);
    webSocket.connect();
```

*PS: I love the library, the efford is greatly appreciated. Aside from this issue it works quite well, is easy to set up and is very thoroughly documented. Thank you!*

**Comment by TakahikoKawasaki** [comment]
It's probably a bug of Android emulator. See [this answer](http://stackoverflow.com/a/4729529/1174054) in StackOverflow and [Issue 3838](https://code.google.com/p/android/issues/detail?id=3838) in Android Issue Tracker.

`nv-websocket-client` itself does not watch the state of network connectivity. Instead, it just does `try-catch` read/write operations. Disconnection is detected by the `try-catch` blocks. See `readFrame()` method in `ReadingThread`.

**Comment by ABoschman** [comment]
Hey TakahikoKawasaki, thanks for the quick response. It might indeed be a bug with the emulator, but it's not the one you linked. 

Contrary to what is described there, I really don't have an internet connection anymore, I can't use the browser and the server I'm supposedly connected to doesn't receive my messages. My problem is that the websocket appears to think it's still connected even though all my other apps agree the internet connection is down.

**Comment by TakahikoKawasaki** [comment]
How do your other apps detect disconnection? If it is achieved by an Android-specific way (e.g. by using `android.permission.ACCESS_NETWORK_STATE`), please do the same and call `WebSocket.disconnect` manually when you detect disconnection. Because `nv-websocket-client` is independent of Android, Android-specific codes need to be written outside `nv-websocket-client`.

**Comment by ABoschman** [comment]
I was starting to suspect that this was gonna be the answer. I will do that, it seems to be the safest and most robust thing to do. 

Thanks for your time, I'll close this issue.
