### ISSUE TITLE
Allow using setServerNames on WebSocket

### ISSUE THREAD

**Issue by MinnDevelopment** [TakahikoKawasaki/nv-websocket-client#201]
Currently, you have to use `WebSocketFactory#setServerNames` for SNI parameters. However, I want to use the factory for different connections to different domains. This requires doing synchronization on the factory only to set the server name:

```java
synchronized (socketFactory) {
    String host = IOUtil.getHost(url);
    // null if the host is undefined, unlikely but we should handle it
    if (host != null)
        socketFactory.setServerName(host);
    else // practically should never happen
        socketFactory.setServerNames(null);
    socket = socketFactory.createSocket(url);
}
```

I have 3 solutions to this problem with decreasing complexity:

1. Allow setting the server names on the socket rather than only the factory, this would require a few changes to the handling of the raw socket creation
1. Allow passing the server names in `createSocket` to have an idempotent behavior
1. Add a way to copy the factory, this should be fairly trivial to implement. For instance `new WebSocketFactory(otherFactory)` or similar. I would be willing to PR this.

**Comment by TakahikoKawasaki** [comment]
@MinnDevelopment Thank you. I'm interested in what your PR will look like 😀 . Please note that I'm a bit picky about beauty of source codes, so PRs that "just work" won't be merged 😅 . My programming style can be found in repositories in [github.com/authlete](https://github.com/authlete) and [github.com/TakahikoKawasaki](https://github.com/TakahikoKawasaki). Finally, I'm sorry I'm busy as a co-founder and programmer of [Authlete, Inc.](https://www.authlete.com/), so it may take time for me to respond.

**Comment by MinnDevelopment** [comment]
@TakahikoKawasaki I already have something but I haven't gotten around to testing it yet. I will try my best to adhere to the code style.
