### ISSUE TITLE
Replace SHA-1 with SHA-2

### ISSUE THREAD

**Issue by Farhad7d7** [TakahikoKawasaki/nv-websocket-client#204]
Many references say that **sha1** algorithm is weak and should be replaced with more secure algorithms e.g **sha2**.
could the **sha1** algorithm used in **handshake** cause any security issue? if yes how can we replace it with **sha2**? thx

**Comment by tarunqss** [comment]
Hey.. Is this issue resolved? Are you able to upgrade to the SHA-256 @Farhad7d7
