### ISSUE TITLE
The websocket gets stuck on connecting with network issues

### ISSUE THREAD

**Issue by fratik** [TakahikoKawasaki/nv-websocket-client#213]
While having weird network issues, the connection process can get stuck in a read operation at random points, like `com.neovisionaries.ws.client.SocketConnector.verifyHostname(SocketConnector.java:271)` or `com.neovisionaries.ws.client.HandshakeReader.readStatusLine(HandshakeReader.java:86)`, which never timeout, even with a  connectTimeout of 10 seconds (https://github.com/DV8FromTheWorld/JDA/issues/1437#issuecomment-723320605).

**Comment by osfunapps** [comment]
Same problem for me

**Comment by Kodehawa** [comment]
Same problem here. Just ran into this.
