### ISSUE TITLE
android integration

### ISSUE THREAD

**Issue by smilecs** [TakahikoKawasaki/nv-websocket-client#22]
These seems like its not creating a connection when implemented on android.......

**Comment by TakahikoKawasaki** [comment]
What do you mean? Do you have any trouble on Android?

**Comment by smilecs** [comment]
i finally got it to create a connection my fault will close issue....sorry about that but am having a problem after like a few minutes likes 5 minutes it gives me an error unexpected end of stream i dont know if the fault is from the server or from me... i cant really tell. p.s the first problem was an exception being thrown because the connection was being made from the main thread. any ideas on the unexpected end of stream

**Comment by TakahikoKawasaki** [comment]
The same issue is reported in #12 and I encountered the error of "The end of the stream has been reached unexpectedly." just now! It seems further investigation is needed...

**Comment by smilecs** [comment]
if i was to apply the hack mentioned in the issue above how can i add the source files as a library. currently adding it to my project through gradle. so tried adding the source files so i could comment the line out any idea on how to do that...sorry am asking this here check alot on google but no clear answer

**Comment by TakahikoKawasaki** [comment]
I found that a certain WebSocket server implementation (`echo.websocket.org`) closes a WebSocket connection without performing a closing handshake if a WebSocket client does not immediately respond to a PING frame sent from the server.

Disconnection without a closing handshake causes `nv-websocket-client` to raise the error of "The end of the stream has reached unexpectedly."

Therefore, I improved the implementation to process PING & PONG frames immediately. After the improvement, the error has not been observed at least in my environment.

Please use the new version `1.16`. It includes the improvement.

**Comment by smilecs** [comment]
thanks a lot tested it out. set the ping interval to 45 seconds.
