### ISSUE TITLE
An uncaught throwable was detected in the writing thread: Attempt to get length of null array

### ISSUE THREAD

**Issue by Behtold** [TakahikoKawasaki/nv-websocket-client#221]
After updating the version (2.10 -> 2.11), the connection is broken with the message "An uncaught throwable was detected in the writing thread: Attempt to get length of null array" after a few seconds. In this case, two identical methods are called simultaneously .onUnexpectedError and .onError. This is not good.

**Comment by TakahikoKawasaki** [comment]
Reportedly, PR #222 fixes this issue. nv-websocket-client 2.12 including #PR 222 has been released.
