### ISSUE TITLE
New version 2.11 doesn't send PONG

### ISSUE THREAD

**Issue by brnostone** [TakahikoKawasaki/nv-websocket-client#223]
After a while debugging my app, I checked version 2.11 with some bug that is not arriving at my PONG frame server, this bug only happens in this version.

**Comment by TakahikoKawasaki** [comment]
The only difference between 2.11 and the previous version was PR #217. Any thoughts, @nosnilmot ?

**Comment by TakahikoKawasaki** [comment]
Is PR #222 related, @nosnilmot ? Anyway, it seems that a new version of nv-websocket-client with PR #222 should be released...

**Comment by TakahikoKawasaki** [comment]
@brnostone I released nv-websocket-client 2.12 including #PR #222. Could you try the new version?

**Comment by nosnilmot** [comment]
Pong frames could be impacted by the empty payload bug in PR 217/fixed by PR 222 if they are in response to a Ping with empty/no payload, or if they are unsolicited periodic pongs.

**Comment by brnostone** [comment]
Now it's working, thanks
