### ISSUE TITLE
Pong payload null exception

### ISSUE THREAD

**Issue by antonmiron** [TakahikoKawasaki/nv-websocket-client#224]
The connection is constantly disrupted (within ~1 minute after connecting) due to the error that "attempt to get lenght of null array" 

I found that the reason is this
![pong](https://user-images.githubusercontent.com/41681541/107746765-3170bc00-6d38-11eb-8a9d-d823c26244db.PNG)

but on line 126 we check that the payload is not null, why not before?

Error:
![pongError](https://user-images.githubusercontent.com/41681541/107746734-228a0980-6d38-11eb-9e10-5cb17f1a3516.PNG)

**Comment by TakahikoKawasaki** [comment]
@antonmiron The bug was fixed by PR #222. nv-websocket-client 2.12 including the bugfix has been released. The bug exists only in nv-websocket-client 2.11 (cf. PR #217).
