### ISSUE TITLE
NPE when WebSocket.sendPing is called due to race condition

### ISSUE THREAD

**Issue by vchau** [TakahikoKawasaki/nv-websocket-client#23]
Hi,
I am using version 1.9 and ran into a race condition with the `WebSocket.mWritingThread` being null when calling WebSocket.sendPing.  Here is the call stack:

```
Caused by java.lang.NullPointerException
       at com.neovisionaries.ws.client.WebSocket.sendFrame(WebSocket.java:1450)
       at com.neovisionaries.ws.client.WebSocket.sendPing(WebSocket.java:1859)
```

The reason this is happening is because I use `WebSocket.connectAsynchronously` in my setup thread but also have another thread that regularly call `WebSocket.sendPing` to keep my connection alive.  The issue is rare as the timer on my pinging thread usually doesn't coincide with a newly created WebSocket object that hasn't yet finished its connection routine.

It would be great if there is a check in `WebSocket.sendPing` or `WebSocket.sendFrame` which ensures the `mWritingThread` is not null or throw an appropriate exception (not NPE).

**Comment by TakahikoKawasaki** [comment]
Use `WebSocket.setPingInterval(long)` method instead of calling `sendPing()` manually.

I'll fix the NPE bug later. Thank you for your report.

BTW, the latest version is `1.17`. Major changes since `1.9` are as follows.

* Performance tuning on `ListenerManager` (1.14)
* Congestion control (1.15)
* RFC 7692 (Compression Extensions for WebSocket) support (1.17)

**Comment by TakahikoKawasaki** [comment]
Dear @vchau 

I released a new version, `1.18`, including the fix for the NPE bug.

**Comment by vchau** [comment]
Thanks @TakahikoKawasaki , I'll try it out your suggestion tomorrow when I have some time.

**Comment by TakahikoKawasaki** [comment]
The bug was fixed. Please reopen this issue if you still encounter the same problem.
