### ISSUE TITLE
[Question] Set a ping timetout ?

### ISSUE THREAD

**Issue by amallo** [TakahikoKawasaki/nv-websocket-client#25]
I would like to handle state where websocket is connected but no data received (eg : you're in subway, your device is connected to 3G but no data received and you cannot send frames).

Is it possible to set a ping timeout ?

**Comment by TakahikoKawasaki** [comment]
You can send ping frames periodically by calling `setPingInterval` method with an interval in milliseconds between ping frames. This method can be called both before and after `connect()` method. Passing zero stops the periodical sending.

```java
// Send a ping per 60 seconds.
ws.setPingInterval(60 * 1000);

// Stop the periodical sending.
ws.setPingInterval(0);
```

Or, the following code although I've not tried it. This will raise `java.net.SocketTimeoutException`.

```java
ws.getSocket().setSoTimeout(60 * 1000);
```

**Comment by amallo** [comment]
Thanks, I will try !
