### ISSUE TITLE
Sending a byte array in pieces.

### ISSUE THREAD

**Issue by germanattanasio** [TakahikoKawasaki/nv-websocket-client#28]
I'm trying to use the library to send an `InputStream` as `byte[]`.

* If I read and send the entire `InputStream`(~600kb) everything works. However, I want to be able to read and send smaller pieces (~4k). 
* If I add a `Thread.sleep(100)` after sending each binary message I works.

Here is the code I'm using:
```java
// A text message arrived from the server.
public void onTextMessage(WebSocket websocket, String message) {  
  if (message != "listening")
    return;

  try {
    byte[] buffer = new byte[4096]; // 4k
    int read;
    while ((read = inputStream.read(buffer)) > 0) {
      if (read == 4096)
        socket.sendBinary(buffer);
      else {
        byte[] last = Arrays.copyOfRange(buffer, 0, read);
        socket.sendBinary(last);
      }
    }
  } catch (IOException e) {
    delegate.onError(e);
  } 
}
```
 - [x] Is there a way to enable debugging?
 - [ ] Which thread is it using to send the audio? could that be the problem?

**Comment by germanattanasio** [comment]
Reading the documentation seems like the problem could be that the `ReadingThread` is calling `sendBinary()`. 

I think I'm completely lost. :astonished:

**Comment by TakahikoKawasaki** [comment]
```java
if (message != "listening")
```

This is a beginners' bug. Use `equals(Object)` method when you compare strings.

**Comment by TakahikoKawasaki** [comment]
Don't write a `while` loop in a callback method such as `onTextMessage`. Program within a callback method should finish as quickly as possible. This rule is not specific to nv-websocket-client. Rather, it is a general rule (i.e. programming basics). If you want to trigger something that takes a long time, it should be done _asynchronously_.

**Comment by TakahikoKawasaki** [comment]
A WebSocket message (text message or binary message) consists of **one or more frames**. `sendBinary()` sends one binary frame and the frame composes one binary message.

If you want to send one binary message that consists of multiple frames, you have to do the following.

1. sendBinary(...data..., false)
2. sendContinuation(...data...)
3. ....
4. sendContinuation(...data..., true)

See _"Send Frames"_ in `README.md` for details.

**Comment by germanattanasio** [comment]
Thanks
