### ISSUE TITLE
Reconnect Socket

### ISSUE THREAD

**Issue by AngellusMortis** [TakahikoKawasaki/nv-websocket-client#3]
I have been going through the code looking for a way to reconnect a socket with no luck. I tried to simply run `.connect()` again on an interval until the connection went through, but I had no luck. It will just keep throwing a WebSocketExpection everytime I try to use `.connect()`. This is what I tried:

    @Override
    public void onDisconnected(WebSocket socket, WebSocketFrame serverCloseFrame,
                               WebSocketFrame clientCloseFrame, boolean closedByServer) {
        if (!closedByServer) {
            RSMCPlugin.Instance.getLogger().warning("Socket disconnected. Will try every 3 seconds until successful");
            this.tryReconnect(socket);
        }
    }

    private void tryReconnect(WebSocket socket) {
        try {
            Thread.sleep(3000);
            socket.connect();
        }
        catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
        catch (WebSocketException e) {
            this.tryReconnect(socket);
        }
    }

I am using version 1.5 from Maven. 

Is this a bug? Is not, can you please update the documentation to show the proper way to attempt reconnecting. 

Also, you library is the only one I have been able to find that works on my WSS server. I am not sure why, but great job!

**Comment by TakahikoKawasaki** [comment]
Thank you for using nv-websocket-client.

The behavior you described is not a bug. It's intended behavior. WebSocket.connect() can be called at most only once.

I'll write a sample code.

**Comment by TakahikoKawasaki** [comment]
I updated `nv-websocket-client` to **version 1.6**. `WebSocket.recreate()` method has been added. The method creates a new `WebSocket` instance that has the same settings as the original instance. So, reconnection can be written like the following.

```java
WebSocket ws = ...;

// Create a new WebSocket instance and connect to the same endpoint.
ws = ws.recreate().connect();
```

Note that, however, settings you made on the raw socket of the original `WebSocket` instance are not copied to the new instance. If you had changed some settings of the raw socket, you have to do it on the new instance again.

**Comment by AngellusMortis** [comment]
That helps a lot. Thanks!

**Comment by nigelnquande** [comment]
Does "If you had changed some settings of the raw socket, you have to do it on the new instance again" include such changes as setting the SSL context and timeout for the `WebSocketFactory` used to initially create the socket?
