### ISSUE TITLE
Reconnect

### ISSUE THREAD

**Issue by shree-ram** [TakahikoKawasaki/nv-websocket-client#31]
public void onDisconnected...{

                        try {
                          
                            // ws = ws.recreate().connect();
                            ws = ws.recreate().connectAsynchronously();                          

                        } catch (Exception e) {                         

                        }
                 }
I've tried to reconnect the socket once server DOWN(Disconnect),  But it's not reconnect the websocket when again server UP(Connected). I suppose to start manually, Websockets is not re-establish the connection. I'm try to implement this websocket for reconnect the websocket once Server is available. But this re-establishment make problem to connect again.

**Comment by TakahikoKawasaki** [comment]
Reconnection fails if it is tried while the server is down. `recreate()` method is not a mechanism to continue to try to connect to the server until a connection is established successfully. If what you want is a mechanism of auto-retrial, you have to implement it by yourself.
