### ISSUE TITLE
Add ability to send headers in the request to create socket

### ISSUE THREAD

**Issue by artem-zinnatullin** [TakahikoKawasaki/nv-websocket-client#32]
Our API needs auth header in the initial request to open websocket but library does not offer overload of `WebSocketFactory.createSocket()` with headers.

**Comment by TakahikoKawasaki** [comment]
**HTTP** headers? If so, call `WebSocket.addHeader(String name, String value)` method after you create an instance of `WebSocket`. The header will be sent to the server when `connect()` is called.

If you want to do [Basic Authentication](https://tools.ietf.org/html/rfc2617#section-2), `WebSocket.setUserInfo(String id, String password)` method is much easier than `addHeader` method.

**Comment by artem-zinnatullin** [comment]
Oh, great! Will try, thanks!
