### ISSUE TITLE
Getting Error when included Library as an external jar to my Android  App 

### ISSUE THREAD

**Issue by raviinder** [TakahikoKawasaki/nv-websocket-client#33]
Hi 

I am getting following error if  i add nv-websocket-client.1.21.jar as an external to my App. 

ClassNotFoundException  i got it. 
Please suggest simplest way to fix it. 

01-26 13:28:38.278: E/AndroidRuntime(18304): FATAL EXCEPTION: AsyncTask #3
01-26 13:28:38.278: E/AndroidRuntime(18304): Process: com.example.websock1, PID: 18304
01-26 13:28:38.278: E/AndroidRuntime(18304): java.lang.RuntimeException: An error occurred while executing doInBackground()
01-26 13:28:38.278: E/AndroidRuntime(18304): 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
01-26 13:28:38.278: E/AndroidRuntime(18304): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
01-26 13:28:38.278: E/AndroidRuntime(18304): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
01-26 13:28:38.278: E/AndroidRuntime(18304): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
01-26 13:28:38.278: E/AndroidRuntime(18304): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
01-26 13:28:38.278: E/AndroidRuntime(18304): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
01-26 13:28:38.278: E/AndroidRuntime(18304): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
01-26 13:28:38.278: E/AndroidRuntime(18304): 	at java.lang.Thread.run(Thread.java:818)
01-26 13:28:38.278: E/AndroidRuntime(18304): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/neovisionaries/ws/client/WebSocketFactory;
01-26 13:28:38.278: E/AndroidRuntime(18304): 	at com.example.websock1.MainActivity$WebSocketOperation.connectWebSocket(MainActivity.java:104)
01-26 13:28:38.278: E/AndroidRuntime(18304): 	at com.example.websock1.MainActivity$WebSocketOperation.doInBackground(MainActivity.java:75)
01-26 13:28:38.278: E/AndroidRuntime(18304): 	at com.example.websock1.MainActivity$WebSocketOperation.doInBackground(MainActivity.java:1)
01-26 13:28:38.278: E/AndroidRuntime(18304): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
01-26 13:28:38.278: E/AndroidRuntime(18304): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-26 13:28:38.278: E/AndroidRuntime(18304): 	... 4 more
01-26 13:28:38.278: E/AndroidRuntime(18304): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.neovisionaries.ws.client.WebSocketFactory" on path: DexPathList[[zip file "/data/app/com.example.websock1-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.websock1-1/lib/arm, /vendor/lib, /system/lib]]
01-26 13:28:38.278: E/AndroidRuntime(18304): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
01-26 13:28:38.278: E/AndroidRuntime(18304): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
01-26 13:28:38.278: E/AndroidRuntime(18304): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
01-26 13:28:38.278: E/AndroidRuntime(18304): 	... 9 more
01-26 13:28:38.278: E/AndroidRuntime(18304): 	Suppressed: java.lang.ClassNotFoundException: com.neovisionaries.ws.client.WebSocketFactory
01-26 13:28:38.278: E/AndroidRuntime(18304): 		at java.lang.Class.classForName(Native Method)
01-26 13:28:38.278: E/AndroidRuntime(18304): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
01-26 13:28:38.278: E/AndroidRuntime(18304): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
01-26 13:28:38.278: E/AndroidRuntime(18304): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
01-26 13:28:38.278: E/AndroidRuntime(18304): 		... 10 more
01-26 13:28:38.278: E/AndroidRuntime(18304): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
01-26 13:28:39.199: E/WindowManager(18304): android.view.WindowLeaked: Activity com.example.websock1.MainActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{8e405fd V.E...... R......D 0,0-1026,486} that was originally added here
01-26 13:28:39.199: E/WindowManager(18304): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:368)
01-26 13:28:39.199: E/WindowManager(18304): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
01-26 13:28:39.199: E/WindowManager(18304): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
01-26 13:28:39.199: E/WindowManager(18304): 	at android.app.Dialog.show(Dialog.java:319)
01-26 13:28:39.199: E/WindowManager(18304): 	at com.example.websock1.MainActivity$WebSocketOperation.onPreExecute(MainActivity.java:70)
01-26 13:28:39.199: E/WindowManager(18304): 	at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:604)
01-26 13:28:39.199: E/WindowManager(18304): 	at android.os.AsyncTask.execute(AsyncTask.java:551)
01-26 13:28:39.199: E/WindowManager(18304): 	at com.example.websock1.MainActivity$1.onClick(MainActivity.java:46)
01-26 13:28:39.199: E/WindowManager(18304): 	at android.view.View.performClick(View.java:5204)
01-26 13:28:39.199: E/WindowManager(18304): 	at android.view.View$PerformClick.run(View.java:21153)
01-26 13:28:39.199: E/WindowManager(18304): 	at android.os.Handler.handleCallback(Handler.java:739)
01-26 13:28:39.199: E/WindowManager(18304): 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-26 13:28:39.199: E/WindowManager(18304): 	at android.os.Looper.loop(Looper.java:148)
01-26 13:28:39.199: E/WindowManager(18304): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
01-26 13:28:39.199: E/WindowManager(18304): 	at java.lang.reflect.Method.invoke(Native Method)
01-26 13:28:39.199: E/WindowManager(18304): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-26 13:28:39.199: E/WindowManager(18304): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by TakahikoKawasaki** [comment]
You simply failed to include nv-websocket-client-1.XX.jar into your project. If you are using Android Studio, open `app/build.gradle` and add the following line into the `dependencies` block.

```gradle
compile 'com.neovisionaries:nv-websocket-client:1.21'
```

**Comment by raviinder** [comment]
I am using eclipse .

**Comment by raviinder** [comment]
Oops I figured it out you were correct .
