### ISSUE TITLE
WebSocket.connect() performs network requests on UI thread on Android

### ISSUE THREAD

**Issue by blunden** [TakahikoKawasaki/nv-websocket-client#4]
Earlier tonight I switched to your WebSocket library since the one I was using had issues with wss:// on Android 5.0 (could be fixed but then it broke on older Android versions). After switching, I noticed that WebSocket.connect() seemingly performs network requests on the UI thread if not manually run on a different thread. The result is that I have to add lots of boilerplate code whenever I want to call my reconnectWebSocket() method. Other WebSocket libraries I looked at avoid doing this.

Is this something you would consider addressing? It would make it behave better on Android and result in cleaner code in the apps using it. Consider it a feature request, not technically an issue per se.

Other than that, it seems pretty solid so far. Good work!

**Comment by TakahikoKawasaki** [comment]
Thank you for your request.

**Comment by vchau** [comment]
+1 on this request. Otherwise, this lib looks like a very clean implementation.

**Comment by TakahikoKawasaki** [comment]
I added `connect(ExecutorService)` and `connectable()` methods to `WebSocket` class and released a new version (1.7) of nv-websocket-client. The following is an excerpt from `README.md` about **Asynchronous Opening Handshake**. If the API does not meet your expectations, let me know.

---


#### Asynchronous Opening Handshake

`connect(ExecutorService)` method is an asynchronous version of `connect()`.
The method performs a WebSocket opening handshake asynchronously using the
given `ExecutorService`.

```java
// Prepare an ExecutorService.
ExecutorService es = Executors.newSingleThreadExecutor();

// Perform an opening handshake asynchronously.
Future<WebSocket> future = ws.connect(es);

try
{
    // Wait for the opening handshake to complete.
    future.get();
}
catch (ExecutionException e)
{
    if (e.getCause() instanceof WebSocketException)
    {
        ......
    }
}
```

The implementation of `connect(ExecutorService)` method creates a
`Callable<WebSocket>` instance by calling `connectable()` method and
passes the instance to `submit(Callable)` method of the given
`ExecutorService`. What the implementation of `call()` method of the
`Callable` instance does is just to call the synchronous `connect()`.

**Comment by blunden** [comment]
I will have to look some more on this later. I think we both hoped the lib would provide something like a simple connect method that would be asynchronous without the application having to create ExecutorServices etc.

**Comment by TakahikoKawasaki** [comment]
Okay. I see.

**Comment by TakahikoKawasaki** [comment]
I added `connectAsynchronously()` method to `WebSocket` and `onConnectError(WebSocket,WebSocketException)` method to `WebSocketListener`, and released a new version (1.8). Below is the description about `connectAsynchronously()`. Asynchronous calls cannot be easier than this.

---

#### Asynchronous Opening Handshake

The simplest way to call `connect()` method asynchronously is to use `connectAsynchronously()` method. The implementation of the method creates a thread and calls `connect()` method in the thread. When the `connect()` call failed, `onConnectError()` of `WebSocketListener` would be called.
Note that `onConnectError()` is called only when `connectAsynchronously()` was used and the `connect()` call executed in the background thread failed. Neither direct synchronous `connect()` nor `connect(ExecutorService)` (described below) will trigger the callback method.

```java
// Perform an opening handshake asynchronously.
ws.connectAsynchronously();
```

**Comment by blunden** [comment]
That sounds very promising. Thanks!

**Comment by blunden** [comment]
Reading this now I realize I might have overstated the need for it to be asynchronous. I don't mind that it locks until the connect is finished, in fact I need it to do so in most cases. The problem was that it performed the network request on the UI thread when used on Android.

I will try out the new version and see if it solves the problem.

**Comment by blunden** [comment]
@vchau Had any chance to try this out yet?

**Comment by vchau** [comment]
Yes, I have. We're going through testing right now but looks very promising.  A couple of recommendation that I found:

- `WebSocketFactory.webcreateSocket()` seems to also be doing some network activity as that also triggered the same exception as `WebSocket.connect()`
- `WebSocket.onError()` callback can be invoked multiple times if there is network lost.  Don't trigger your reconnect routine on this unless you want a flood of reconnect attempt. `onDisconnected()` seems better suited.
- If you have custom TLS configurations, see issue #6

**Comment by TakahikoKawasaki** [comment]
Released a new version, **1.20**. `Socket.connect()` was moved from `WebSocketFactory.createSocket()` to `WebSocket.connect()`. So, probably `WebSocketFactory.createSocket()` can be called in the main thread. If Android still complains about `createSocket()`, we have to give up calling `createSocket()` in the main thread. Please see #26 for details.

**Comment by or-else** [comment]
The issue remains. It's due to name resolution. I'll file details in another bug.

**Comment by TakahikoKawasaki** [comment]
@or-else The new version `1.22` includes the fix. Thank you.
