### ISSUE TITLE
Callbacks are slow?

### ISSUE THREAD

**Issue by gurpreet-** [TakahikoKawasaki/nv-websocket-client#40]
Whenever I'm streaming binary data, either the data is received slowly or the callback is taking a long time to get called. 

Just a little context surrounding this, I'm streaming images in binary form from a server and rendering them on screen in Android. I know that there is some 'choking' going on with the Android client because I'm also streaming and rendering to a browser client and on the browser it's delay free. However when I stream to the Android client there is some delay.

Just to clarify, at the start of the stream there is absolutely no delay, but after around 5 seconds, the images received start to slow down (as in, they go in slow motion), which possibly points to the Android library doing some extra processing that slows down the callbacks being called (or my asynchronous `LinkedBlockingQueue` implementation being just badly done).

Here is some code:

```java
public class MainActivity extends AppCompatActivity {

    private LinkedBlockingQueue<byte[]> linkedBlockingQueue = new LinkedBlockingQueue<byte[]>();
    private boolean keepRunning = true;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        ...
        new MyRenderer().start();
        ...
    }

    // Decodes and renders a bitmap
    private class MyRenderer extends Thread {
        @Override
        public void run() {
            // Keep running this thread
            while (keepRunning) {
                // .take() blocks until we have more data
                final byte[] bitmapArray = linkedBlockingQueue.take();
                final Bitmap bitmap = BitmapFactory.decodeByteArray(bitmapArray, 0, bitmapArray.length);

                // Set bitmap to an imageview
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        someImageView.setImageBitmap(bm);
                    }
                });
            }
        }
    }

    // We'll create a websocket listener as a class field and
    // set it to a websocket later
    WebSocketAdapter websocketAdapter = new WebSocketAdapter() {
        ....
        @Override
        public void onBinaryMessage(WebSocket websocket, byte[] bitmapArray) throws Exception {
            super.onBinaryMessage(websocket, bitmapArray);
            // Add the binary bitmap to the queue for processing in the above thread
            linkedBlockingQueue.put(bitmapArray);
        }
        ...
    }

   // Create websocket, set the websocketAdapter to a websocket, etc

}
```

Are there any pointers you could give me? Perhaps there's something that I'm doing stupidly wrong?

I would also be interested to know if you will be supporting a streaming websocket. As in one that I could easily perform `websocket.read()` for example, because that would mean I could pipe the data out to an `OutputStream` for forwarding or simply to read data in a new thread in an easy manner.

<hr />

**Library version:** 1.22
**Android compileSdkVersion:** 23
**Android minSdkVersion:** 19

Fantastic library + documentation by the way :+1:

**Comment by TakahikoKawasaki** [comment]
It is needed to find the point that consumes time too much. So, why don't you measure how much time `BitmapFactory.decodeByteArray()` consumes? In addition, printing out the size of `linkedBlockingQueue` around `put()` and `take()` operations will give you some hints.

**Comment by gurpreet-** [comment]
Many thanks for the reply.

You were right, the callbacks are not slow at all, it was actually my producer-consumer (the `linkedBlockingQueue`) implementation filling up. I have changed the code to a better implementation, namely I have used an `ArrayBlockingQueue` instead.

Thanks for your help :smile:

**Comment by TakahikoKawasaki** [comment]
I'm glad to hear you've solved the problem.
