### ISSUE TITLE
Move notifyFinished to finally block in ReadingThread

### ISSUE THREAD

**Issue by avasenin** [TakahikoKawasaki/nv-websocket-client#46]
We had a lot of leaked sockets in CLOSE_WAIT state and a lot of active leaked PingTimers threads.

After some digging I's able to reproduce the scenario which causes a leak. The main reason of this is fixed in #23 when you add a check before send https://github.com/TakahikoKawasaki/nv-websocket-client/blob/master/src/main/java/com/neovisionaries/ws/client/WebSocket.java#L2213 We upgraded the version and everything works fine.

In general we had the following scenario:
1) `TCP FIN` packet come.
2) https://github.com/TakahikoKawasaki/nv-websocket-client/blob/master/src/main/java/com/neovisionaries/ws/client/ReadingThread.java#L306 this call fires WebSocketException
3) This exception passed to user's callback here https://github.com/TakahikoKawasaki/nv-websocket-client/blob/master/src/main/java/com/neovisionaries/ws/client/ReadingThread.java#L345
4) User call `disconnect` in onError callback to make sure that socket is closed
5) `disconnect` call sets `null` to `mReadingThread` and `mWritingThread`
6) ReadingThread tries to send close frame https://github.com/TakahikoKawasaki/nv-websocket-client/blob/master/src/main/java/com/neovisionaries/ws/client/ReadingThread.java#L352
7) `sendFrame` throws NullPointerException because mWritingThread is null
8) `notifyFinished` is not called and `WebSocket.finish` isn't called too too https://github.com/TakahikoKawasaki/nv-websocket-client/blob/master/src/main/java/com/neovisionaries/ws/client/ReadingThread.java#L114 Pinger handles link to WebSocket object and doesn't allow gc call `finilize` method. This was a reason of socket and PingerTimer leak

Why am I writing the ticket if everything is working fine in the new version? Good question!

As postmortem of my investigation, I'm really want to ask you to move `notifyFinished` call to `finally` block here https://github.com/TakahikoKawasaki/nv-websocket-client/blob/master/src/main/java/com/neovisionaries/ws/client/ReadingThread.java#L74 to make sure that ReadingThread calls `onReadingThreadFinished` in all cases to avoid such issues in future.

Thanks,

**Comment by TakahikoKawasaki** [comment]
Thank you very much for your detailed investigation. I moved the position of the call of `notifyFinished()` to the end of `main()` method.

The new version, `1.25`, contains the changes.

**Comment by avasenin** [comment]
Thanks!

Just asking why you didn't wrap it to `finally` block? If any exception was thrown in `catch` clause then `notifyFinished` would not be called, right? As I know it's not possible but you need to know how `ListenerManager` works internally to be sure with it.

**Comment by TakahikoKawasaki** [comment]
It's because I know the implementation of `ListenerManager`.

`callOnXxx` methods never throw any `Throwable`.

**Comment by avasenin** [comment]
Your speed and level of support is amazing.

Thanks,
