### ISSUE TITLE
which method i can use if pc WIFI shutdown

### ISSUE THREAD

**Issue by zhangkou** [TakahikoKawasaki/nv-websocket-client#47]
Hi,

The following methods are not called after i close my pc wifi,which method i can use if pc WIFI shutdown

@Override
    public void onCloseFrame(WebSocket websocket, WebSocketFrame frame) throws Exception  {
    }
    @Override
    public void onError(WebSocket websocket, WebSocketException cause) throws Exception  {
    }
    @Override
    public void onMessageError(WebSocket websocket,WebSocketException cause, List<WebSocketFrame> frames) throws Exception {
    }
    @Override
    public void onUnexpectedError(WebSocket websocket,WebSocketException cause) throws Exception {
    }
    
    @Override
    public void onConnectError(WebSocket websocket, WebSocketException exception) throws Exception {
    }

    @Override
    public void onFrameError(WebSocket websocket, WebSocketException cause, WebSocketFrame frame){
    	
    }

    @Override
    public void onTextMessageError(WebSocket websocket, WebSocketException cause, byte[] data){
    
    }

    @Override
    public void onSendError(WebSocket websocket, WebSocketException cause, WebSocketFrame frame){
    
    }
    @Override
    public void onStateChanged(WebSocket websocket, WebSocketState newState) throws Exception {

    }
    
    @Override
    public void handleCallbackError(WebSocket websocket, Throwable cause) throws Exception{
    	
    }

    @Override
    public void onSendingHandshake(WebSocket websocket, String requestLine, List<String[]> headers) throws Exception{
    }

Thanks.
coco.

**Comment by zhangkou** [comment]
getState() still is OPEN after i close my wifi manually.

**Comment by TakahikoKawasaki** [comment]
Even if WiFi is turned off, errors may not be detected immediately if data are not being transmitted through a WebSocket connection. But this behavior may vary depending on the environment you use. When nv-websocket-client detects an error after a WebSocket connection is established, `onError` method is always called and other `onXxxError` method(s) may be called additionally depending on the context of the error.

You can raise an error by sending a [ping frame](https://tools.ietf.org/html/rfc6455#section-5.5.2) (by `sendPing()` method) after you turn WiFi off.
