### ISSUE TITLE
Thread.interrupt() doesn't unblock socket's InputStream.read()

### ISSUE THREAD

**Issue by avasenin** [TakahikoKawasaki/nv-websocket-client#48]
Hi,

We are using the ping/pong functionality to check connectivity between a client and a server. If we don't receive pong responses from the server we are calling `disconnect` method. 

`disconnect` method tries to interrupt `ReadingThread` which is blocked on `read()` operation. The main issue the socket's input stream has a platform specific behaviour when thread is interrupted. For example, it doesn't work on my Mac OS oracle jdk 1.6 & 1.8. ReadingThread is waiting on `readFrame` forever after `disconnect`. Apparently `interrupt()` approach doesn't work for unblocking socket I/O on "most" modern Java platforms [stackoverflow]. As I know only `close()` has note in javadoc about throwing SocketException in threads blocked in an I/O operation.

Right now I'm using webSocket.getSocket().close() after `disconnect()` method to explicitly unblock all I/O operation but it causes a lot of exception from websocket library.

It will be great to have more stable disconnect behaviour. 

[stackoverflow]: http://stackoverflow.com/a/4426050/1406317

**Comment by TakahikoKawasaki** [comment]
Thank you for your feedback. Please give me some time.

**Comment by avasenin** [comment]
I suppose that this issue and https://github.com/TakahikoKawasaki/nv-websocket-client/issues/29 are related.

**Comment by TakahikoKawasaki** [comment]
@avasenin I released a new version, `1.26`. I think this issue and #29 have been fixed. It would be appreciated if you could spare time to try the new version.

**Comment by avasenin** [comment]
Thanks, I will check it on the next week

**Comment by TakahikoKawasaki** [comment]
@avasenin I'm closing this issue. Please let me know if this issue reproduces.
