### ISSUE TITLE
WebSocket is closing when device sleeps.

### ISSUE THREAD

**Issue by chrisdew** [TakahikoKawasaki/nv-websocket-client#49]
A few seconds after the screen goes off, the (https over gprs) websocket connection closes.
```
04-12 16:39:23.534  15149-15201/com.foo.bar D/NativeCrypto﹕ ssl=0x61bd9e98 info_callback where=0x4004 ret=256
04-12 16:39:23.534  15149-15201/com.foo.bar D/NativeCrypto﹕ ssl=0x61bd9e98 SSL3 alert read:W:CN warning close notify
04-12 16:39:23.534  15149-15201/com.foo.bar D/NativeCrypto﹕ ssl=0x61bd9e98 info_callback ignored
04-12 16:39:23.536  15149-15201/com.foo.bar E/CommsService﹕ error
    com.neovisionaries.ws.client.WebSocketException: The end of the stream has been reached unexpectedly.
            at com.neovisionaries.ws.client.WebSocketInputStream.readBytes(WebSocketInputStream.java:153)
            at com.neovisionaries.ws.client.WebSocketInputStream.readFrame(WebSocketInputStream.java:44)
            at com.neovisionaries.ws.client.ReadingThread.readFrame(ReadingThread.java:306)
            at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:93)
            at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:61)
```

(The code then opens a new connection, and the futile cycle continues...)

How can I avoid this?  I want the websocket to stay listening for packets from the server, while the phone sleeps.

(I have made "connection stays listening while device sleeps" work for a plain TCP connection before, but websocket connections are behaving differently.)

**Comment by avasenin** [comment]
Library uses the plain Socket under the hood. It shouldn't behave differently then plan TCP connection. This error returns when socket read returns `-1`.

How do you store your WebSocket object (in Activity or Service)?

**Comment by chrisdew** [comment]
The WebSocket object is stored in a Service.

**Comment by eku** [comment]
Check out https://stackoverflow.com/questions/13534732/how-to-make-the-android-device-hold-a-tcp-connection-to-internet-without-wake-lo

**Comment by chrisdew** [comment]
The set up I am trying to make work is:

App<--WebSocket-Upgrade-over-HTTPS-->Nginx<--Unencrypted-WebSocket-->NodeJS

It works fine when the WebSocket is being actively used, but a few tens of seconds after the screen goes dark, the WebSocket connection breaks.

If I make the app connect directly (unencrypted) to the NodeJS service, there is no problem.

I've used Wireshark to look at the issue and have seem the following, which may be causing Nginx to close the HTTPS TCP connection, after a timeout.

When I send from the App, using: `ws.sendText(gson.toJson(message));` I see the following packet arrive at the server (whether using Nginx or not):
```
WebSocket
1... .... = Fin: True
.00 .... = Reserved: 0x00
.... 0001 = Opcode: Text (1)
1... .... = Mask: True
.100 1001 = Payload length: 73
```

I should stress that this is a WebSocket FIN, not a TCP FIN.

The arrival of a WebSocket frame with a FIN flag set does not seem to cause any trouble for NodeJS (i.e. the connection remains open and working) but it does *seem* to cause Nginx to close the corresponding HTTPS connection, when Nginx is used.

Why does nv-websocket-client set the WebSocket FIN flag, on a simple `ws.sendText`?

Does the WebSocket FIN flag singal the end of the connection, or just the last frame of a message?

**Comment by chrisdew** [comment]
Looks like the FIN is a red herring.  It's probably an Nginx proxy_read_timeout thing...  I will confirm.

**Comment by chrisdew** [comment]
Yes, `proxy_read_timeout` was the problem.
