### ISSUE TITLE
addListener onConnected never called

### ISSUE THREAD

**Issue by webblong** [TakahikoKawasaki/nv-websocket-client#52]
when connect successfully , onConnected/onTextMessage never called , i don't know why , how to solve it ?

.addListener(new WebSocketAdapter() {
                    @Override
                    public void onConnected(WebSocket websocket, Map<String, List<String>> headers) {
                        Timber.e("onConnected-----------");
                    }

**Comment by TakahikoKawasaki** [comment]
How did you know that a connection was established successfully if `onConnected` was not called? Some more code, please.

**Comment by webblong** [comment]
Sorry to say that it's the server using pure socket instead of WebSocket .

2016-05-12 13:49 GMT+08:00 Takahiko Kawasaki <notifications@github.com>:
