### ISSUE TITLE
How to send message with event to NodeJS server using Socket.IO

### ISSUE THREAD

**Issue by MaximeLignereux** [TakahikoKawasaki/nv-websocket-client#53]
Hi!

I would like use your library but I don't know how to send a message and a event.
 
Here is an example of a method in my server:

io.sockets.on('connection', function(socket){
  socket.on('deleteEvent', function(timeline_id, event_id){
    socket.emit("delete");
  });
});

Can you help me please ??

Thank you

**Comment by TakahikoKawasaki** [comment]
In the WebSocket protocol ([RFC 6455](https://tools.ietf.org/html/rfc6455)) , there is no concept called 'event'. I'm afraid that what you are talking about is specific to [Socket.IO](http://socket.io/).
