### ISSUE TITLE
Never see a timeout

### ISSUE THREAD

**Issue by amirlatifi** [TakahikoKawasaki/nv-websocket-client#54]
When I try to connect to a WS server which is down, I won't receive any timeout exception or error in my adapter. 

The state changes to CONNECTING (onSendingHandshake) and the it stuck on this stage forever. I setConnectionTimeout to something about 1000 MS.

I tried to set timeout to very low value to see whether it's working or not. When I use for example 1 or 10 MS as timeout. The connection after this time closes and I can see timeout error properly.

**Comment by amirlatifi** [comment]
I was using ver. 1.22. I've tried 1.27 and this issue seems fixed. Thanks.

**Comment by TakahikoKawasaki** [comment]
I'm glad to hear it.
