### ISSUE TITLE
Suscrible channel

### ISSUE THREAD

**Issue by Guryanov** [TakahikoKawasaki/nv-websocket-client#56]
Hello! How to subscribe websocket channel?

**Comment by TakahikoKawasaki** [comment]
There is no concept called "channel" in the WebSocket protocol ([RFC 6455](https://tools.ietf.org/html/rfc6455)). Are you talking about [MQTT](http://mqtt.org/) over WebSocket? nv-websocket-client does not have features related to MQTT over WebSocket.
