### ISSUE TITLE
how to write int progurad  file

### ISSUE THREAD

**Issue by happycodinggirl** [TakahikoKawasaki/nv-websocket-client#58]
after proguard ,websocket connect throw Exception ,doubt how to proguard,please help me!Thank you !

**Comment by TakahikoKawasaki** [comment]
Hmm... No idea. Please show me the stack trace of the exception.

**Comment by eku** [comment]
We are using nv-wensockets on Android without any special proguard rules. As @TakahikoKawasaki  wrote, please provide a stacktrace.

**Comment by happycodinggirl** [comment]
sorry, i described wrong, i hava resolved it .The exception is not the cause of proguard ,it becauses i connect websocket on the main thread ,now i moved it to the third thread ,it's ok! I do not do anything in proguard, it  has been ok.Thanks !

**Comment by TakahikoKawasaki** [comment]
I see. Okay.
