### ISSUE TITLE
PerMessageDeflateExtension sometime have java.nio.BufferOverflowException

### ISSUE THREAD

**Issue by ayking** [TakahikoKawasaki/nv-websocket-client#59]
I found it throws by byte[] decompress(byte[] compressed) and I attached the compressed data triggered this exception
[-20, -38, 49, 13, 0, 0, 0, 2, -96, -2, -83, 45, -95, -101, 7, 29, 56, 81, 115, -43, 92, 53, 87, -51, -35, 106, 81, 115, -43, 92, 53, 87, -51, 85, 115, -43, 92, 53, 87, -51, -67, -47, -93, -26, -86, -71, 106, -82, -102, -85, -26, -86, -71, 106, -82, -102, -85, -26, 62, 120, -87, -43, -36, 0]

**Comment by TakahikoKawasaki** [comment]
Thank you for your report. I'll investigate it.

**Comment by TakahikoKawasaki** [comment]
@ayking 
Released a new version, 1.28, to include the #60 patch by @jszczygiel which may solve this issue. Please try the new version.

**Comment by TakahikoKawasaki** [comment]
Please let me know if you encounter the error again.

**Comment by ayking** [comment]
@TakahikoKawasaki Oh, sorry I still not have time to test it.
