### ISSUE TITLE
WebSocketFactory.setSSLContext() and WebSocketFactory.setSSLSocketFactory() should not allow both to be set.

### ISSUE THREAD

**Issue by vchau** [TakahikoKawasaki/nv-websocket-client#6]
Thanks, I've gotten this library to work on KitKat and Lollipop in my app.  Much much easier to use than AndroidAsync!!!

Here's is a suggestion for improving your API.

I made the mistake of calling both WebSocketFactory.setSSLContext() and WebSocketFactory.setSSLSocketFactory() when I wanted it to use my own SSLSocketFactory.  It turned out that if I pass the context, it will never use the factory instance I gave it.

You should either not allow the above, or when SocketFactorySettings.selectSocketFactory() is called, use the factory instance that was provided if not null first, else use an instance from the SSLContext.

**Comment by TakahikoKawasaki** [comment]
As for SSL settings, README.md says "See the [description](http://takahikokawasaki.github.io/nv-websocket-client/com/neovisionaries/ws/client/WebSocketFactory.html#createSocket-java.net.URI-) of `WebSocket.createSocket` method for details." And the JavaDoc clearly describes how a socket factory is selected.

```
A socket factory (= a SocketFactory instance) to create a raw socket
(= a Socket instance) is determined as described below.

1. If the scheme of the URI is either wss or https,
    i. If an SSLContext instance has been set by setSSLContext(SSLContext),
       the value returned from SSLContext.getSocketFactory() method of the
       instance is used.

   ii. Otherwise, if an SSLSocketFactory instance has been set by
       setSSLSocketFactory(SSLSocketFactory), the instance is used.

  iii. Otherwise, the value returned from SSLSocketFactory.getDefault() is used. 

2. Otherwise (= the scheme of the URI is either ws or http),
    i. If a SocketFactory instance has been set by setSocketFactory(SocketFactory),
        the instance is used.

   ii. Otherwise, the value returned from SocketFactory.getDefault() is used.
```

Why do you think `SSLSocketFactory` should take precedence over `SSLContext`? It's just your preference, isn't it? The reason my implementation prioritizes `SSLContext` over `SSLSocketFactory` is that `SSLSocketFactory` can be obtained from `SSLContext` but `SSLContext` cannot be obtained from `SSLSocketFactory`.

Also, there is no good reason to disallow `setSSLSocketFactory()` method call after `setSSLContext()` method call (or vice versa). Such a meddling check would make `WebSocketFactory` class awkward to use.

It is difficult for me to imagine a case where people want to call both `setSSLContext()` and `setSSLSocketFactory()`. My assumption is that people will call only one of `setSSLContext()`, `setSSLSocketFactory()` and `setSocketFactory()`, or call none of them.

**Comment by vchau** [comment]
@TakahikoKawasaki As it is, this is just a suggestion.  

It was my fault for not reading the documentation in details first before calling both methods.  But how many other developers do you think will read the documentation in details first before making the same mistake? :smile:

**Comment by TakahikoKawasaki** [comment]
Updated `README.md`. Below is an excerpt. This is the best I can do.

<hr/>

By default, `WebSocketFactory` uses `SocketFactory.getDefault()` for non-secure WebSocket connections (`ws:`) and `SSLSocketFactory.getDefault()` for secure WebSocket connections (`wss:`). You can change this default behavior by using `WebSocketFactory.setSocketFactory` method, `WebSocketFactory.setSSLSocketFactory` method and `WebSocketFactory.setSSLContext` method. Note that you don't have to call a `setSSL*` method at all if you use the default SSL configuration. <b>Also note that calling `setSSLSocketFactory` method has no meaning if you have called `setSSLContext` method. See the [description](http://takahikokawasaki.github.io/nv-websocket-client/com/neovisionaries/ws/client/WebSocketFactory.html#createSocket-java.net.URI-) of `WebSocketFactory.createSocket(URI)` method for details</b>.

The following is an example to set a custom SSL context to a `WebSocketFactory` instance. (Again, you don't have to call a `setSSL*` method if you use the default SSL configuration.)
