### ISSUE TITLE
WebSocketExceptionError: not CREATED

### ISSUE THREAD

**Issue by jackanmol** [TakahikoKawasaki/nv-websocket-client#68]
This error is flashing on trying to connect to the server. What I would be missing?
**com.neovisionaries.ws.client.WebSocketException: The current state of the web socket is not CREATED**

**Comment by TakahikoKawasaki** [comment]
`connect` method can be called at most only once. What is returned if you call `getState()` method? If you want to reconnect to the server using the same configuration as an existing `WebSocket` instance, try `recreate()` method.

**Comment by TakahikoKawasaki** [comment]
Reopen this issue if you can provide more info.

**Comment by de5car7es** [comment]
Hi.

Closing a socket, calling recreate and then connect doesnt seem to work.
You get "The current state of the WebSocket is not CREATED."
```

                        try {
                            if (webSocket.getState() == WebSocketState.CLOSED)
                                    webSocket.recreate();

                            webSocket.connect();

                        }
                        catch (WebSocketException e1)
                        {
                            Log.e(TAG, "WebSocketException exception: " + e1.getMessage());
                        }
                        catch (Exception e)
                        {
                            Log.e(TAG, "Exception: " + e.getMessage());
                        }
```

**Comment by MinnDevelopment** [comment]
@de5car7es recreate returns a new WebSocket to use:

```java
if (webSocket.getState() == WebSocketState.CLOSED)
    webSocket = webSocket.recreate();

webSocket.connect();
```

See the [source](https://github.com/TakahikoKawasaki/nv-websocket-client/blob/5c13e99c72e7ee324915213ddf60dbe0d184d956/src/main/java/com/neovisionaries/ws/client/WebSocket.java#L1151-L1179) for documentation.
