### ISSUE TITLE
Connect stopped working on Mon, 18. July 2016

### ISSUE THREAD

**Issue by jonathanbergen** [TakahikoKawasaki/nv-websocket-client#69]
We have nv-websocket running on production with Nexus4 (Cyanogenmod) devices. All of them stopped working today at the same time. We get the following connection failure message:

`Failed to get the input stream of the raw socket: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x52f6bd70: Failure in SSL library, usually a protocol error
error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (external/openssl/ssl/s23_clnt.c:744 0x513b9d74:0x00000000)`

I am also not able to connect using my Macbook running OSX.

Though using my LG G4, it does work. 

Any idea what could cause this issue?

**Comment by TakahikoKawasaki** [comment]
I think some changes have been made in your SSL environment. For example, possible root causes are:

1. Smartphone OS update
2. Server-side SSL configuration change
3. SSL Certificate expiration

Especially, check whether TLS version has been changed.

**Comment by jonathanbergen** [comment]
Thank you for your quick response!

**Switching to** `TLSv1.2` **solved the issue for us.**

So the issue was not related to the nv-websocket implementation and can be closed.

Our provider disabled SSL3. Obviously the OS we used (Android 4.4.4) took that as default protocol. Anyways, SSL3 [shouldn't be used](http://disablessl3.com/) nowadays.
