### ISSUE TITLE
WebSocketAdapter.onError() vs WebSocketAdapter.onDisconnected()

### ISSUE THREAD

**Issue by vchau** [TakahikoKawasaki/nv-websocket-client#7]
Seems like onError() can be invoked multiple times for many different things.  I triggered this three times when I turned off Wifi on my Android device.  onDisconnected() was triggered once.

Belows were from onError():
```
com.neovisionaries.ws.client.WebSocketException: An I/O error occurred while a frame was being read from the web socket.
com.neovisionaries.ws.client.WebSocketException: Flushing frames to the server failed
com.neovisionaries.ws.client.WebSocketException: Flushing frames to the server failed
```

If I just wanted to be callback whenever I need to re-initiate the websocket connection, regardless of the error, which callback should I register for?

Seems like onDisconnected() is all I need?

**Comment by TakahikoKawasaki** [comment]
`onError()` is always called before other `onXxxError()` methods are called. It is designed so intentionally. See _Error Handling_ in `README.md`.

After `WebSocket.connect()` succeeded, `onDisconnected()` is always called. If `connect()` failed, `onDisconnected()` will not be called. Note that `onConnectError()` is called when `connect()` failed, so if `onConnectError()` was called, `onDisconnected()` will not be called.

**Comment by vchau** [comment]
Ok, thanks. I think I'll just register for `onConnectError()` and `onDisconnect()` since I really can't do much else with other callback bug log the event.
