### ISSUE TITLE
OpeningHandshakeException / '101 Switching Protocols'. The status line is: HTTP/1.1 503 Endpoint Creation Failed

### ISSUE THREAD

**Issue by MikeMitterer** [TakahikoKawasaki/nv-websocket-client#71]
Hi, First of all - Thanks for your lib!

Im working on a "Websocket-Autoconnector". First connection works like a charm but after restarting to server (Embedded Jetty 9.2.18.v20160721 runs within Docker 1.12) I get: `com.neovisionaries.ws.client.OpeningHandshakeException: The status code of the opening handshake response is not '101 Switching Protocols'. The status line is: HTTP/1.1 503 Endpoint Creation Failed`

This is the relevant code part:
```java
                ...
                final URI uri = uriBuilderForWebSocket.queryParam(QUERY_PARAM, ticket).build();

                return Observable.create(new Observable.OnSubscribe<AbstractDataEvent>() {

                    @Override
                    public void call(final Subscriber<? super AbstractDataEvent> subscriber) {
                        // Create a WebSocket. The timeout value set above is used.
                        try {
                            // Makes null check, disconnects if "isOpen"
                            disconnectWebSocket();

                            factory = new WebSocketFactory().setConnectionTimeout(5000);
                            webSocket = factory.createSocket(uri);
                            webSocket.addListener(bindSignals(subscriber));

                            // signal.await();
                            webSocket.connect();

                        } catch (final ConnectException e) {
                            connecting = false;
                            logger.warn("Connection failed: {}", e.getMessage());

                        } catch (Exception e) {
                            connecting = false;
                            subscriber.onError(e);
                        }
                    }
                });
```
I also tried "reconnect" but with the same result. As said - if the server runs everything works fine error occurs after restarting the server. Any ideas?

**Comment by TakahikoKawasaki** [comment]
In general, it takes some time for a server to get ready to start serving. `503 Unavailable` implies that your server is not ready yet. In a project where I myself uses nv-websocket-client, reconnection to a server is repeated with [exponential backoff](exponential backoff).

[com.google.api.client.util.ExponentialBackOff](https://developers.google.com/api-client-library/java/google-http-java-client/reference/1.20.0/com/google/api/client/util/ExponentialBackOff) is one example that implements the exponential backoff algorithm. See also [Exponential Backoff](https://developers.google.com/api-client-library/java/google-http-java-client/backoff) (Google API Client Libraries).

**Comment by MikeMitterer** [comment]
The code snipped I posted is already called by an "exponential" ticker. The server runs fine, accepts "normal" http calls. It also works if I restart the client manually... (In this case its a integration test)

**Comment by TakahikoKawasaki** [comment]
1. Basically, `503 Unavailable` is a server error. The server log may give you some hints.
2. Some HTTP proxies don't support WebSocket well. The proxy logs may give you some hints.
3. What is the value of `uri` on the client side when reconnection fails? Isn't there any difference between on failure and on success?
4. What if you change `wss:` to `ws:`? (if you are using `wss:`.)

**Comment by MikeMitterer** [comment]
I tested it with okhtt-ws - same result. 
The uri is different. It connects via ticket. e.g. ws://localhost:80/service?ticketid=123 next attempt is e.g. ws://localhost:80/service?ticketid=abc.

I'm using ws: seems to be a Jetty-problem. I tried to avoid to upgrade Jetty but this will be my next step. Anyway - thanks for your help.
