### ISSUE TITLE
App Crashes on Samsung S3/S4 API 18/21 when opening web socket with hostname

### ISSUE THREAD

**Issue by hadaska** [TakahikoKawasaki/nv-websocket-client#74]
I'm trying to use your WebSocket client in my Android app and so far things seems great, except for this issue I just ran into:

Testing on Samsung Galaxy S3, API 18, and also Samsung Galaxy S4 API 21, I got this exception when calling WebSocketFactory.createSocket(URI uri) with a hostname URI instead of ip + port:
java.lang.RuntimeException: Unable to resume activity : java.lang.IllegalArgumentException: The host part is empty.

Trying to debug I see that on WebSocketFactoy line 481, the host gets a null value, while on other devices (API 23) it gets the value of the hostname. Also, if I use ip+port the value of host is correct. (Tried to use hostname:port but also got the same problem) 

I really hope you can provide a solution because I really want to use your library, other than this small issue it is great and so much better than anything else I tried!

**Comment by TakahikoKawasaki** [comment]
Okay. I'll try to implement a workaround.

**Comment by TakahikoKawasaki** [comment]
Released a new version, 1.30, which includes a workaround for the issue. Please try the new version.

If not only `URI.getHost()` but also the entire implementation of `URI` class is wrong (= if neither `URI.getRawAuthority()` nor `URI.toString()` works correctly) on the Samsung devices, even the workaround may not work. In such a case, let me know again.

**Comment by hadaska** [comment]
Thank you so much for responding so quickly and for fixing this!
The new version 1.30 does solve the issue. 
Closing.
