### ISSUE TITLE
Provide MaxPayload.

### ISSUE THREAD

**Issue by bksantiago** [TakahikoKawasaki/nv-websocket-client#8]
Hello,

Can you provide a max payload property, which lets the library send it by fragments if it reaches the maximum payload.

Thanks,
Great work btw

**Comment by TakahikoKawasaki** [comment]
Just out of curiosity, I'm interested in whether such a feature is actually needed or not. Do you have any use-case for the feature?

**Comment by Marc1510** [comment]
@TakahikoKawasaki I actually have. For an service there is a max payload of 4MB per frame. I have a file of maybe 20MB read into memory in a byte array but it would be ideal if the library could split the file for me.

**Comment by TakahikoKawasaki** [comment]
@Marc1510 Thank you for your feedback. I'll implement the feature in the near future.

**Comment by TakahikoKawasaki** [comment]
@bksantiago @Marc1510
Implemented a mechanism to set the maximum payload size and released a new version `1.27`. The following is a document about the new feature.

<hr>
#### Maximum Payload Size

You can set an upper limit on the payload size of WebSocket frames by calling `setMaxPayloadSize(int)` method with a positive value. Text, binary and continuation frames whose payload size is bigger than the maximum payload size you have set will be split into multiple frames.

```java
// Set 1024 as the maximum payload size.
ws.setMaxPayloadSize(1024);
```

Control frames (close, ping and pong frames) are never split as per the specification.

If permessage-deflate extension is enabled and if the payload size of a WebSocket frame after compression does not exceed the maximum payload size, the WebSocket frame is not split even if the payload size before compression exceeds the maximum payload size.

**Comment by TakahikoKawasaki** [comment]
@bksantiago @Marc1510 I'm closing this issue. If you find a bug in this new feature, please let me know.

**Comment by eku** [comment]
Now that we have a framer for sending splitting data, what about deframing received splitted data?

**Comment by TakahikoKawasaki** [comment]
@eku 
A WebSocket **message** consists of one or more WebSocket **frames**.

`onFrame()` method (and a following `onXxxFrame()` method) is called for each of incoming fragmented frames, while `onTextMessage()` method and `onBinaryMessage()` method are called for text messages and binary messages, respectively.

Messages you receive via `onTextMessage()` method and `onBinaryMessage()` method are results of concatenation of one or more WebSocket frames.
