### ISSUE TITLE
Slow in read inputStream

### ISSUE THREAD

**Issue by saeedrooyekhat** [TakahikoKawasaki/nv-websocket-client#82]
I have a problem in read data from server when i send data to server when i want get response , read from input stream blocked because available bytes from input stream is zero and i have to wait about 1 second and after this time i get response. 

in WebSocketInputStream . readBytes method 

`int count = read(buffer, total, length - total);`

**Comment by TakahikoKawasaki** [comment]
If it takes 1 second for the first data to arrive at the client from the server, it is natural it takes 1 second for `read()` to respond to the first data. What is the problem?

**Comment by saeedrooyekhat** [comment]
excuse me i ask question badly .  i want upload file with socket in 250kb chunk . i guess my data not sent to  server yet and read method block at that line and waiting for first send data and second notify from server and finally i get available data.

how can i detect time from send binary during my data really sent to server?

i user from onFrameSent but this time is about 200millisecond and my delay is about 1 second or more.
befor i call sendBinary method i get x=currentTimeMillis and when run onFrameSent compute difference between currentTimeMillis-x=200.

another thing it is that when my client (Android phone) is stronger my delay is lower!

**Comment by TakahikoKawasaki** [comment]
I don't understand your situation well, but one or combination of the following may solve your problem.

1. Use <code>WebSocket.[setMaxPayloadSize](http://takahikokawasaki.github.io/nv-websocket-client/com/neovisionaries/ws/client/WebSocket.html#setMaxPayloadSize-int-)(int size)</code>
2. Call <code>WebSocket.[flush()](http://takahikokawasaki.github.io/nv-websocket-client/com/neovisionaries/ws/client/WebSocket.html#flush--)</code>
3. Divide the data into one binary frame and following continuation frames manually and send them one by one. (See [my answer](http://stackoverflow.com/a/29780169/1174054) to the question "[Websockets- send binary data as chunks](http://stackoverflow.com/q/29629330/1174054)" in StackOverflow.)

Note that <code>WebSocketListener.[onFrameSent](http://takahikokawasaki.github.io/nv-websocket-client/com/neovisionaries/ws/client/WebSocketListener.html#onFrameSent-com.neovisionaries.ws.client.WebSocket-com.neovisionaries.ws.client.WebSocketFrame-)(WebSocket, WebSocketFrame)</code> is called before **flush is performed** as written in its JavaDoc.

> Called when a WebSocket frame was sent to the server (but **not flushed yet**).

**Comment by saeedrooyekhat** [comment]
thanks for your answer . but my problem not solve yet.

my another question is when flush performed This means that client working is finished and really sent data?
i ask this question from you because i want sure about send time .

**Comment by TakahikoKawasaki** [comment]
<code>WebSocket.flush()</code> method ensures that <code>java.io.OutputStream.[flush()](http://docs.oracle.com/javase/8/docs/api/java/io/OutputStream.html#flush--)</code> is called and nothing more than it.

Note that **buffering is implemented in various layers**. Under <code>OutputStream.flush()</code>, a networking protocol stack of your operating system and a hardware layer of your device exist. They have a buffering mechanism. In addition, various networking devices and servers such as routers and HTTP proxies that exist between your WebSocket client and your WebSocket server have a buffering mechanism.

One means to know the exact time is to make your WebSocket server send back a message including timestamp when the server receives a message from your client. The client can compute the round-trip time.

**Comment by TakahikoKawasaki** [comment]
For example, the following code is wrong.

```java
long start = System.currentTimeMillis();
ws.sendBinary(message);
ws.flush();
long end = System.currentTimeMillis();
long elapsed = end - start; // wrong
```

It's because what `WebSocket.flush()` does is just to queue a flush request. To be exact, `WebSocket.flush()` calls `WritingThread.queueFlush()` and the implementation of `WritingThread.queueFlush()` is this:

```java
public void queueFlush()
{
    synchronized (this)
    {
        mFlushNeeded = true;

        // Wake up this thread.
        notifyAll();
    }
}
```

As you can see, **`WebSocket.flush()` does not call `java.io.OutputStream.flush()` synchronously.**

**Comment by TakahikoKawasaki** [comment]
Please reopen this issue if necessary.
