### ISSUE TITLE
Socket disconnected

### ISSUE THREAD

**Issue by maximsushkevich** [TakahikoKawasaki/nv-websocket-client#83]
Hello there,

I use this socket library in ddp client for android.
I have found that socket destroys connection  every 10 - 40 sec.

Has anybody met the problem such this?

**Comment by twogood** [comment]
Have you tried on different networks? Some firewalls are very aggressive about closing "idle" sockets.

**Comment by maximsushkevich** [comment]
Looks like problem is gone. Maybe it really was problem with network.

Thank you!
