### ISSUE TITLE
Send byte array to server (Exception is badly formatted)

### ISSUE THREAD

**Issue by ThuanvdLe** [TakahikoKawasaki/nv-websocket-client#85]
I use your library to send byte array (converted from json string) to ws server and I got exception
Here is exception and my code:
Exception: 
 com.neovisionaries.ws.client.WebSocketException: The status line of the opening handshake response is badly formatted. The status line is: �v�The client frame set the reserved bits to [4] for a message with opCode [7] which was not supported by this endpoint<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">

My code:

    final byte[] byteArr = data.getBytes();
        try {
            WebSocketFactory factory = new WebSocketFactory();
            final WebSocket socket = factory.createSocket(wss);
            final String userPassword = userName + ":" + password;
            final String encodeAuthorization = Base64.encodeToString(userPassword.getBytes(), Base64.NO_WRAP);
            socket.addHeader("Authorization", "Basic " + encodeAuthorization);
            socket.addListener(new WebSocketAdapter() {
                // receive text
                @Override
                public void onTextMessage(WebSocket websocket, String text) throws Exception {
                    super.onTextMessage(websocket, text);
                    Log.d("WebSocketManager", text);
                }

                // receive byte
                @Override
                public void onBinaryMessage(WebSocket websocket, byte[] binary) throws Exception {
                    super.onBinaryMessage(websocket, binary);
                    String s = new String(binary);
                    Log.d("WebSocketManager", s);
                    JSONObject jsonResult = new JSONObject(s.toString());
                    boolean result = jsonResult.getBoolean("result_cd");
                    //boolean result = true;
                    // callback to set response result
                    if(mRequestCompletedListener != null) {
                        mRequestCompletedListener.onRequestCompletedListener(RequestType.REQ_POST_PRESENT_LOCATION, String.valueOf(result));
                    }
                    if (result) {
                        Log.d("WebSocketManager", "Transmit present location info : SUCCESS");
                    } else {
                        Log.d("WebSocketManager", "Transmit present location info : FAIL");
                    }
                }

                // called when connect successful
                @Override
                public void onConnected(WebSocket websocket, Map<String, List<String>> headers) throws Exception {
                    super.onConnected(websocket, headers);
                    Log.d("WebSocketManager", "Connect");
                    // send data
                    socket.sendBinary(byteArr, false);
                }

                @Override
                public void onDisconnected(WebSocket websocket, WebSocketFrame serverCloseFrame, WebSocketFrame clientCloseFrame, boolean closedByServer) throws Exception {
                    super.onDisconnected(websocket, serverCloseFrame, clientCloseFrame, closedByServer);
                    Log.d("WebSocketManager", "Disconnect");
                }
            });
            socket.connect();

        } catch (WebSocketException e) {
            Log.d("WebSocketManager", e.toString());
            if(mRequestCompletedListener != null) {
                mRequestCompletedListener.onRequestCompletedListener(RequestType.REQ_POST_PRESENT_LOCATION, "FAIL");
            }
        } catch (IOException e) {
            e.printStackTrace();
            Log.d("WebSocketManager", e.toString());
        }

Please help me.
Thank you very much

**Comment by ThuanvdLe** [comment]
I am sorry 
I send one frame
 // send data
 socket.sendBinary(byteArr);

**Comment by TakahikoKawasaki** [comment]
The first line from the server should look like this:

    HTTP/1.1 101 Switching Protocols

but the error message implies that the server returned binary data. Check the URL to access, especially the scheme part (`ws:` or `wss:`).

BTW, you can replace this code

    final String userPassword = userName + ":" + password;
    final String encodeAuthorization = Base64.encodeToString(
        userPassword.getBytes(), Base64.NO_WRAP);
    socket.addHeader("Authorization", "Basic " + encodeAuthorization);

with this code

    socket.setUserInfo(userName, password);

**Comment by ThuanvdLe** [comment]
My server is not support binary data
Thank you very much your support
