### ISSUE TITLE
onConnected isn't called when using connectAsynchronously()

### ISSUE THREAD

**Issue by a-reisberg** [TakahikoKawasaki/nv-websocket-client#88]
`onConnected` isn't called when using `connectAsynchronously()`. Is it only called when using `connect()`?
Thanks.

**Comment by TakahikoKawasaki** [comment]
Hmm... `onConnected()` should be called. What `connectAsynchronously()` does is just to create and start a new thread whose `run()` method calls `connect()`. The following is the implementation of `WebSocket.connectAsynchronously()`:

```java
public WebSocket connectAsynchronously()
{
    new ConnectThread(this).start();

    return this;
}
```

And the implementation of `run()` of `ConnectThread` is this:

```java
@Override
public void run()
{
    try
    {
        mWebSocket.connect();
    }
    catch (WebSocketException e)
    {
        handleError(e);
    }
}
```

Could you please make sure that your code override `onConnected(WebSocket websocket, Map<String,List<String>> headers)` correctly?

**Comment by TakahikoKawasaki** [comment]
The difference between (1) calling `connectAsynchronously()` and (2) calling `connect()` directly is not related to whether `onConnected()` is called or not.

Please reopen this issue if necessary.
