### ISSUE TITLE
Cannot reconnect to Websocket

### ISSUE THREAD

**Issue by phihochzwei** [TakahikoKawasaki/nv-websocket-client#90]
Hi there, 

here I have something really strange for you. 

We are using you library to establish a connection between an Android Wear Device (V 1.5) and a WebSocket. The device is paired with a Samsung Galaxy S5 (latest Android). When our app first starts (Watch is connected via bluetooth to Mobile), everything works fine and as expected. If then the Bluetooth connection is cut (for whatever reason), the Watch switches to WIFI and also connects as intended. When you now reconnect the Watch to the Mobile via Bluetooth, the WebSocket connection does not get established. Turn Bluetooth off, it works, back on, connection dead. Only solution is, to reboot the Watch (which actually is no solution :) )

One "funny" thing to mention: When you get the Network-Type on the Watch while connected via Bluetooth, it returns the type "PROXY" (constant value is 16) which actually is NOWHERE documented. And when you try to get the DefaultProxy-Information vom the ConnectivityManager, it returns a null

**Comment by phihochzwei** [comment]
And here is the message thrown, when trying to connect 

`com.neovisionaries.ws.client.WebSocketException: Failed to connect to 'XXXX:3000': Host is unresolved: XXXX
at com.neovisionaries.ws.client.SocketConnector.doConnect(SocketConnector.java:119)
at com.neovisionaries.ws.client.SocketConnector.connect(SocketConnector.java:81)
at com.neovisionaries.ws.client.WebSocket.connect(WebSocket.java:2022)
at com.neovisionaries.ws.client.ConnectThread.run(ConnectThread.java:37)
Caused by: java.net.UnknownHostException: Host is unresolved: XXXX
at java.net.Socket.connect(Socket.java:867)
at com.neovisionaries.ws.client.SocketConnector.doConnect(SocketConnector.java:110)`

**Comment by phihochzwei** [comment]
I would be really thankful for any help

**Comment by phihochzwei** [comment]
After purchasing an Acer and a LG Phone, I can confirm that this is not related to the known "Samsung cannot resolve URI"-Problems

**Comment by TakahikoKawasaki** [comment]
I'm sorry I don't understand your issue well enough, but it seems that the error message says `XXXX` is an invalid host name. Is it an actual error message, or did you replace an actual host name with `XXXX` before pasting the error message here?

If `"Host is unresolved"` is the root cause, it's not a WebSocket issue but a DNS issue.

**Comment by phihochzwei** [comment]
Maybe the problem gets clearer when I explain the steps to reproduce:

1. Wear-Device connected to Internet via Bluetooth over Smartphone -> Host can be resolved and WebSocket connects
2. Turn off Bluetooth on Wear-Device
3. Wear-Device connected via WiFi directly -> Host can be resolved and WebSockets connects
4. Turn on Bluetooth on Wear-Device
5. Wear-Device connected to Internet via Bluetooth over Smartphone (again) -> Host cannot be resolved and WebSocket cant connect. Never again. Until you manually reboot the Wear-Device. Then it all start´s at 1.

**Comment by TakahikoKawasaki** [comment]
Well, then, it sounds that the root cause exists in the network layer in Wear-Device. A WebSocket library cannot do anything for the problem...
