### ISSUE TITLE
how disable mask

### ISSUE THREAD

**Issue by saeedrooyekhat** [TakahikoKawasaki/nv-websocket-client#92]
how can i disable mask in webSocket?

**Comment by TakahikoKawasaki** [comment]
Describe more.

**Comment by saeedrooyekhat** [comment]
i want to connect to socket and send request and get response without using mask for reducing the use of data in connection and make it faster.

**Comment by TakahikoKawasaki** [comment]
To achieve the special behavior, both a WebSocket client and a WebSocket server must agree on it. If there were a WebSocket [extension](https://tools.ietf.org/html/rfc6455#section-9) for the behavior, it could be implemented. However, I don't know such an extension. Considering the historical reason of [masking](https://tools.ietf.org/html/rfc6455#section-5.3), it is unlikely that such an extension is developed in the future.

**Comment by saeedrooyekhat** [comment]
my server cleared mask and i want clear mask for agree with that. of course i read Considering the historical reason of masking and i consciously want do that

**Comment by TakahikoKawasaki** [comment]
It sounds that you have your own WebSocket server, right?

Correct WebSocket server implementations have to _unmask_ frames sent from WebSocket clients, but are you intentionally going to implement a different behavior?

**Comment by saeedrooyekhat** [comment]
yes we have own WebSocket server . i want send request without masking for server and Server without unmasking use the message

**Comment by TakahikoKawasaki** [comment]
A right approach is defined a new WebSocket extension for the behavior. On the other hand, an easy way is to add a special method to `WebSocket` class to control the behavior.

**Comment by saeedrooyekhat** [comment]
how can set mask to zero
https://tools.ietf.org/html/rfc6455#section-5.2

**Comment by saeedrooyekhat** [comment]
i use three step for disable mask
1- `public void write(WebSocketFrame frame) throws IOException {
        writeFrame0(frame);
        writeFrame1(frame);
        writeFrameExtendedPayloadLength(frame);

        // Generate a random masking key.

        // Write the masking key.
        if (WebSocket.useMask) {
            byte[] maskingKey = Misc.nextBytes(4);
            write(maskingKey);

            // Write the payload.
            writeFramePayload(frame, maskingKey);
        } else {
            writeFramePayload(frame, null);
        }
    }`
2 - `private void writeFrame1(WebSocketFrame frame) throws IOException {
        // Frames sent from a client are always masked.
        int b;
        if (WebSocket.useMask) {
            b = 0x80;
        } else {
            b = 0x00;
        }

        int len = frame.getPayloadLength();

        if (len <= 125) {
            b |= len;
        } else if (len <= 65535) {
            b |= 126;
        } else {
            b |= 127;
        }

        write(b);
    }`

3- `private void writeFramePayload(WebSocketFrame frame, byte[] maskingKey) throws IOException {
        byte[] payload = frame.getPayload();

        if (payload == null) {
            return;
        }
        for (int i = 0; i < payload.length; ++i) {

            // Mask
            int b;
            if (WebSocket.useMask) {
                b = (payload[i] ^ maskingKey[i % 4]) & 0xFF;
            } else {
                b = (payload[i]) & 0xFF;
            }

            // Write
            write(b);
        }
    }`

**Comment by TakahikoKawasaki** [comment]
Well, sorry, but the problem is not how to implement the feature but whether it is worth implementing the feature. If the special behavior is only for your closed project, no one else wants the feature unless, for example, the project is beneficial to society.
