### ISSUE TITLE
Socket Disconnect In Android 7 (Xiaomi Phone)

### ISSUE THREAD

**Issue by saeedrooyekhat** [TakahikoKawasaki/nv-websocket-client#93]
in Xiaomi Phone when network change state and disabled, WebSocket Disconnect or Error not called.
and also when checking that websocket is open the result was true.
how can detect socket disconnected in android 7?

**Comment by alilotfi** [comment]
@saeedrooyekhat 
I'm experiencing the same issue, could you please explain did you solve it or not?
