### ISSUE TITLE
WebSocketException should extend IOException instead of Exception

### ISSUE THREAD

**Issue by or-else** [TakahikoKawasaki/nv-websocket-client#95]
For consistency with java.net.* packages, WebSocketException should extend either java.io.IOException or java.net.SocketException. The current non-standard WebSocketException requires catching it specifically, as opposed to a generic flow of catching an IOException if WS-specific error handling is not needed.

**Comment by blunden** [comment]
Agreed.

**Comment by TakahikoKawasaki** [comment]
I'm sorry for my lack of foresight. However, it is wise to avoid adopting the change that breaks backward compatibility.
