### ISSUE TITLE
Write data in parallel state

### ISSUE THREAD

**Issue by saeedrooyekhat** [TakahikoKawasaki/nv-websocket-client#97]
how can write data in parallel state in one socket connection?

**Comment by saeedrooyekhat** [comment]
I ask my question more fully.
when client sending a big file with socket that for example send the file time is 10 minutes. now i want before sending files over , send another file with higher priority and do this actions just in one connection.
now when i do this action have a delay for sending second file. is there any way i send files to prioritize
or write some information apart from each other to have no interference with each other?

**Comment by TakahikoKawasaki** [comment]
A text message can be split into multiple frames. To be specific, a text message can be split into one leading text frame and subsequent continuation frames. Controls frames (such as ping frame) can be interleaved into the split frames. However, data frames cannot be mixed.

To put it simply, the WebSocket protocol does not support your use case. So, you need to use multiple WebSocket connections to send multiple files in parallel.
